# <span style='color:white'> <center>Manejo de datos con Pandas</center> </span>
## 1. Análisis Exploratorio
<p><img src="https://online.york.ac.uk/wp-content/uploads/2021/07/man-in-a-suit-standing-behind-a-hologram-of-data-analytics-1030x579.jpg" width="750"</p>

## Explorando un DataFrame
<p>Cuando trabajamos con DataFrames, es un bueno comenzar por explorarlo y analizar su contenido.
    
<code>homelessnes</code> es un dataset que contiene estimaciones de la falta de vivienda en cada estado de EE. UU. en 2018. La columna <code>individual</code> es el número de personas sin hogar que no forman parte de una familia con niños. La columna <code>family_members</code> es el número de personas sin hogar que forman parte de una familia con niños. La columna <code>state_pop</code> es la población total del estado. </p>

In [44]:
#Importar la libreria pandas
import pandas as pd

#Realizar la lectura del archivo csv homelessness
homelessness =pd.read_csv('C:\\Users\\rebec\\python-basics\\Data excel para manejo de librería Pandas\\homelessness.csv', 
    header=0,
    dtype={'region':'str'})

In [36]:
# Imprimir las primeras 5 lineas de mi DataFrame
display(homelessness)

,region,state,individuals,family_members,state_pop
0,East South Central,Alabama,2570,864,4887681
1,Pacific,Alaska,1434,582,735139
2,Mountain,Arizona,7259,2606,7158024
3,West South Central,Arkansas,2280,432,3009733
4,Pacific,California,109008,20964,39461588
5,Mountain,Colorado,7607,3250,5691287
6,New England,Connecticut,2280,1696,3571520
7,South Atlantic,Delaware,708,374,965479
8,South Atlantic,District of Columbia,3770,3134,701547
9,South Atlantic,Florida,21443,9587,21244317
10,South Atlantic,Georgia,6943,2556,10511131
11,Pacific,Hawaii,4131,2399,1420593
12,Mountain,Idaho,1297,715,1750536
13,East North Central,Illinois,6752,3891,12723071
14,East North Central,Indiana,3776,1482,6695497
15,West North Central,Iowa,1711,1038,3148618
16,West North Central,Kansas,1443,773,2911359
17,East South Central,Kentucky,2735,953,4461153
18,West South Central,Louisiana,2540,519,4659690
19,New England,Maine,1450,1066,1339057
20,South Atlantic,Maryland,4914,2230,6035802
21,New England,Massachusetts,6811,13257,6882635
22,East North Central,Michigan,5209,3142,9984072
23,West North Central,Minnesota,3993,3250,5606249
24,East South Central,Mississippi,1024,328,2981020
25,West North Central,Missouri,3776,2107,6121623
26,Mountain,Montana,983,422,1060665
27,West North Central,Nebraska,1745,676,1925614
28,Mountain,Nevada,7058,486,3027341
29,New England,New Hampshire,835,615,1353465
30,Mid-Atlantic,New Jersey,6048,3350,8886025
31,Mountain,New Mexico,1949,602,2092741
32,Mid-Atlantic,New York,39827,52070,19530351
33,South Atlantic,North Carolina,6451,2817,10381615
34,West North Central,North Dakota,467,75,758080
35,East North Central,Ohio,6929,3320,11676341
36,West South Central,Oklahoma,2823,1048,3940235
37,Pacific,Oregon,11139,3337,4181886
38,Mid-Atlantic,Pennsylvania,8163,5349,12800922
39,New England,Rhode Island,747,354,1058287
40,South Atlantic,South Carolina,3082,851,5084156
41,West North Central,South Dakota,836,323,878698
42,East South Central,Tennessee,6139,1744,6771631
43,West South Central,Texas,19199,6111,28628666
44,Mountain,Utah,1904,972,3153550
45,New England,Vermont,780,511,624358
46,South Atlantic,Virginia,3928,2047,8501286
47,Pacific,Washington,16424,5880,7523869
48,South Atlantic,West Virginia,1021,222,1804291
49,East North Central,Wisconsin,2740,2167,5807406
50,Mountain,Wyoming,434,205,577601

In [42]:
homelessness =pd.read_csv('C:\\Users\\rebec\\python-basics\\Data excel para manejo de librería Pandas\\homelessness.csv',
 header=0,
 usecols=['region','state'])

In [41]:
display(homelessness)

                region                 state
0   East South Central               Alabama
1              Pacific                Alaska
2             Mountain               Arizona
3   West South Central              Arkansas
4              Pacific            California
5             Mountain              Colorado
6          New England           Connecticut
7       South Atlantic              Delaware
8       South Atlantic  District of Columbia
9       South Atlantic               Florida
10      South Atlantic               Georgia
11             Pacific                Hawaii
12            Mountain                 Idaho
13  East North Central              Illinois
14  East North Central               Indiana
15  West North Central                  Iowa
16  West North Central                Kansas
17  East South Central              Kentucky
18  West South Central             Louisiana
19         New England                 Maine
20      South Atlantic              Maryland
21         New England         Massachusetts
22  East North Central              Michigan
23  West North Central             Minnesota
24  East South Central           Mississippi
25  West North Central              Missouri
26            Mountain               Montana
27  West North Central              Nebraska
28            Mountain                Nevada
29         New England         New Hampshire
30        Mid-Atlantic            New Jersey
31            Mountain            New Mexico
32        Mid-Atlantic              New York
33      South Atlantic        North Carolina
34  West North Central          North Dakota
35  East North Central                  Ohio
36  West South Central              Oklahoma
37             Pacific                Oregon
38        Mid-Atlantic          Pennsylvania
39         New England          Rhode Island
40      South Atlantic        South Carolina
41  West North Central          South Dakota
42  East South Central             Tennessee
43  West South Central                 Texas
44            Mountain                  Utah
45         New England               Vermont
46      South Atlantic              Virginia
47             Pacific            Washington
48      South Atlantic         West Virginia
49  East North Central             Wisconsin
50            Mountain               Wyoming

##Imprimir todo el Data Frame

In [48]:
display(homelessness)

,region,state,individuals,family_members,state_pop
0,East South Central,Alabama,2570,864,4887681
1,Pacific,Alaska,1434,582,735139
2,Mountain,Arizona,7259,2606,7158024
3,West South Central,Arkansas,2280,432,3009733
4,Pacific,California,109008,20964,39461588
5,Mountain,Colorado,7607,3250,5691287
6,New England,Connecticut,2280,1696,3571520
7,South Atlantic,Delaware,708,374,965479
8,South Atlantic,District of Columbia,3770,3134,701547
9,South Atlantic,Florida,21443,9587,21244317
10,South Atlantic,Georgia,6943,2556,10511131
11,Pacific,Hawaii,4131,2399,1420593
12,Mountain,Idaho,1297,715,1750536
13,East North Central,Illinois,6752,3891,12723071
14,East North Central,Indiana,3776,1482,6695497
15,West North Central,Iowa,1711,1038,3148618
16,West North Central,Kansas,1443,773,2911359
17,East South Central,Kentucky,2735,953,4461153
18,West South Central,Louisiana,2540,519,4659690
19,New England,Maine,1450,1066,1339057
20,South Atlantic,Maryland,4914,2230,6035802
21,New England,Massachusetts,6811,13257,6882635
22,East North Central,Michigan,5209,3142,9984072
23,West North Central,Minnesota,3993,3250,5606249
24,East South Central,Mississippi,1024,328,2981020
25,West North Central,Missouri,3776,2107,6121623
26,Mountain,Montana,983,422,1060665
27,West North Central,Nebraska,1745,676,1925614
28,Mountain,Nevada,7058,486,3027341
29,New England,New Hampshire,835,615,1353465
30,Mid-Atlantic,New Jersey,6048,3350,8886025
31,Mountain,New Mexico,1949,602,2092741
32,Mid-Atlantic,New York,39827,52070,19530351
33,South Atlantic,North Carolina,6451,2817,10381615
34,West North Central,North Dakota,467,75,758080
35,East North Central,Ohio,6929,3320,11676341
36,West South Central,Oklahoma,2823,1048,3940235
37,Pacific,Oregon,11139,3337,4181886
38,Mid-Atlantic,Pennsylvania,8163,5349,12800922
39,New England,Rhode Island,747,354,1058287
40,South Atlantic,South Carolina,3082,851,5084156
41,West North Central,South Dakota,836,323,878698
42,East South Central,Tennessee,6139,1744,6771631
43,West South Central,Texas,19199,6111,28628666
44,Mountain,Utah,1904,972,3153550
45,New England,Vermont,780,511,624358
46,South Atlantic,Virginia,3928,2047,8501286
47,Pacific,Washington,16424,5880,7523869
48,South Atlantic,West Virginia,1021,222,1804291
49,East North Central,Wisconsin,2740,2167,5807406
50,Mountain,Wyoming,434,205,577601

In [50]:
##Imprimir las primeras 5 filas
display(homelessness.head(5))

               region       state  individuals  family_members  state_pop
0  East South Central     Alabama         2570             864    4887681
1             Pacific      Alaska         1434             582     735139
2            Mountain     Arizona         7259            2606    7158024
3  West South Central    Arkansas         2280             432    3009733
4             Pacific  California       109008           20964   39461588

In [51]:
##Imprimir las últimas 5 líneas de mi DataFrame
display(homelessness.tail(5))

                region          state  individuals  family_members  state_pop
46      South Atlantic       Virginia         3928            2047    8501286
47             Pacific     Washington        16424            5880    7523869
48      South Atlantic  West Virginia         1021             222    1804291
49  East North Central      Wisconsin         2740            2167    5807406
50            Mountain        Wyoming          434             205     577601

In [52]:
##Imprimir 5 lineas aleatorias de mi DataFrame
display(homelessness.sample(5))

                region       state  individuals  family_members  state_pop
31            Mountain  New Mexico         1949             602    2092741
15  West North Central        Iowa         1711            1038    3148618
12            Mountain       Idaho         1297             715    1750536
23  West North Central   Minnesota         3993            3250    5606249
37             Pacific      Oregon        11139            3337    4181886

In [53]:
# Imprimir la información de los campos de mi DataFrame
display(homelessness.info())

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   region          51 non-null     str
 1   state           51 non-null     str
 2   individuals     51 non-null     int64
 3   family_members  51 non-null     int64
 4   state_pop       51 non-null     int64
dtypes: int64(3), str(2)
memory usage: 3.2 KB

None

In [55]:
##Traerme filas específicas de mi Data Frame en este caso de la 10 a la 12
display(homelessness[10:13])

            region    state  individuals  family_members  state_pop
10  South Atlantic  Georgia         6943            2556   10511131
11         Pacific   Hawaii         4131            2399    1420593
12        Mountain    Idaho         1297             715    1750536

In [59]:
##Método para localizar una coordenada de mi DataFrame
homelessness.iloc[3,2]

np.int64(2280)

In [60]:
##Uso del iterador for para correr en un DataFrame de Pandas
for i in range (0,50):
    a = homelessness.iloc[i,2]
    calculo = a+ 10
    print(calculo)

2580
1444
7269
2290
109018
7617
2290
718
3780
21453
6953
4141
1307
6762
3786
1721
1453
2745
2550
1460
4924
6821
5219
4003
1034
3786
993
1755
7068
845
6058
1959
39837
6461
477
6939
2833
11149
8173
757
3092
846
6149
19209
1914
790
3938
16434
1031
2750

In [66]:
##Conocer la longitud de alguna columna de mi DataFrame
len(homelessness['region'])

51

In [67]:
# Imprimir el tamaño (#filas, #columnas) de mi DataFrame
homelessness.shape

(51, 5)

In [68]:
# Imprimir la estadística descriptiva básica de mi DataFrame
homelessness.describe()

         individuals  family_members     state_pop
count      51.000000       51.000000  5.100000e+01
mean     7225.784314     3504.882353  6.405637e+06
std     15991.025083     7805.411811  7.327258e+06
min       434.000000       75.000000  5.776010e+05
25%      1446.500000      592.000000  1.777414e+06
50%      3082.000000     1482.000000  4.461153e+06
75%      6781.500000     3196.000000  7.340946e+06
max    109008.000000    52070.000000  3.946159e+07

## Partes un DataFrame
<p>Para comprender mejor la estructura de un DataFrame, es útil saber que constan de tres componentes, almacenados como atributos:
<ul>
<li><code>.values</code> muestra una matriz de valores NumPy bidimensional</li>
<li><code>.columns</code> muestra índice de columnas: los nombres de las columnas.</li>
<li><code>.index</code> muestra índice para las filas: números de fila o nombres de fila.</li>
</ul>
</p>

In [71]:
# Imprimir los valores de mi DataFrame
homelessness.values

array([['East South Central', 'Alabama', 2570, 864, 4887681],
       ['Pacific', 'Alaska', 1434, 582, 735139],
       ['Mountain', 'Arizona', 7259, 2606, 7158024],
       ['West South Central', 'Arkansas', 2280, 432, 3009733],
       ['Pacific', 'California', 109008, 20964, 39461588],
       ['Mountain', 'Colorado', 7607, 3250, 5691287],
       ['New England', 'Connecticut', 2280, 1696, 3571520],
       ['South Atlantic', 'Delaware', 708, 374, 965479],
       ['South Atlantic', 'District of Columbia', 3770, 3134, 701547],
       ['South Atlantic', 'Florida', 21443, 9587, 21244317],
       ['South Atlantic', 'Georgia', 6943, 2556, 10511131],
       ['Pacific', 'Hawaii', 4131, 2399, 1420593],
       ['Mountain', 'Idaho', 1297, 715, 1750536],
       ['East North Central', 'Illinois', 6752, 3891, 12723071],
       ['East North Central', 'Indiana', 3776, 1482, 6695497],
       ['West North Central', 'Iowa', 1711, 1038, 3148618],
       ['West North Central', 'Kansas', 1443, 773, 2911359],
       ['East South Central', 'Kentucky', 2735, 953, 4461153],
       ['West South Central', 'Louisiana', 2540, 519, 4659690],
       ['New England', 'Maine', 1450, 1066, 1339057],
       ['South Atlantic', 'Maryland', 4914, 2230, 6035802],
       ['New England', 'Massachusetts', 6811, 13257, 6882635],
       ['East North Central', 'Michigan', 5209, 3142, 9984072],
       ['West North Central', 'Minnesota', 3993, 3250, 5606249],
       ['East South Central', 'Mississippi', 1024, 328, 2981020],
       ['West North Central', 'Missouri', 3776, 2107, 6121623],
       ['Mountain', 'Montana', 983, 422, 1060665],
       ['West North Central', 'Nebraska', 1745, 676, 1925614],
       ['Mountain', 'Nevada', 7058, 486, 3027341],
       ['New England', 'New Hampshire', 835, 615, 1353465],
       ['Mid-Atlantic', 'New Jersey', 6048, 3350, 8886025],
       ['Mountain', 'New Mexico', 1949, 602, 2092741],
       ['Mid-Atlantic', 'New York', 39827, 52070, 19530351],
       ['South Atlantic', 'North Carolina', 6451, 2817, 10381615],
       ['West North Central', 'North Dakota', 467, 75, 758080],
       ['East North Central', 'Ohio', 6929, 3320, 11676341],
       ['West South Central', 'Oklahoma', 2823, 1048, 3940235],
       ['Pacific', 'Oregon', 11139, 3337, 4181886],
       ['Mid-Atlantic', 'Pennsylvania', 8163, 5349, 12800922],
       ['New England', 'Rhode Island', 747, 354, 1058287],
       ['South Atlantic', 'South Carolina', 3082, 851, 5084156],
       ['West North Central', 'South Dakota', 836, 323, 878698],
       ['East South Central', 'Tennessee', 6139, 1744, 6771631],
       ['West South Central', 'Texas', 19199, 6111, 28628666],
       ['Mountain', 'Utah', 1904, 972, 3153550],
       ['New England', 'Vermont', 780, 511, 624358],
       ['South Atlantic', 'Virginia', 3928, 2047, 8501286],
       ['Pacific', 'Washington', 16424, 5880, 7523869],
       ['South Atlantic', 'West Virginia', 1021, 222, 1804291],
       ['East North Central', 'Wisconsin', 2740, 2167, 5807406],
       ['Mountain', 'Wyoming', 434, 205, 577601]], dtype=object)

In [72]:
# Imprimir el nombre de mis campos (columnas) de mi DataFrame
homelessness.columns

Index(['region', 'state', 'individuals', 'family_members', 'state_pop'], dtype='str')

In [73]:
# Imprimir el indice de mi DataFrame
homelessness.index

RangeIndex(start=0, stop=51, step=1)

## Ordenando filas de un DataFrame
<p>Encontrar datos interesantes en un DataFrame suele ser más fácil si cambiamos el orden de las filas. Podemos ordenar las filas pasando un nombre de columna al método <code>.sort_values()</code>. </p>

In [78]:
# Ordena el DataFrame por la columna 'individual'
homelessness_ind= homelessness.sort_values(by='individuals', ascending=True)
# Imprime el resultado
display(homelessness_ind)

,region,state,individuals,family_members,state_pop
50,Mountain,Wyoming,434,205,577601
34,West North Central,North Dakota,467,75,758080
7,South Atlantic,Delaware,708,374,965479
39,New England,Rhode Island,747,354,1058287
45,New England,Vermont,780,511,624358
29,New England,New Hampshire,835,615,1353465
41,West North Central,South Dakota,836,323,878698
26,Mountain,Montana,983,422,1060665
48,South Atlantic,West Virginia,1021,222,1804291
24,East South Central,Mississippi,1024,328,2981020
12,Mountain,Idaho,1297,715,1750536
1,Pacific,Alaska,1434,582,735139
16,West North Central,Kansas,1443,773,2911359
19,New England,Maine,1450,1066,1339057
15,West North Central,Iowa,1711,1038,3148618
27,West North Central,Nebraska,1745,676,1925614
44,Mountain,Utah,1904,972,3153550
31,Mountain,New Mexico,1949,602,2092741
3,West South Central,Arkansas,2280,432,3009733
6,New England,Connecticut,2280,1696,3571520
18,West South Central,Louisiana,2540,519,4659690
0,East South Central,Alabama,2570,864,4887681
17,East South Central,Kentucky,2735,953,4461153
49,East North Central,Wisconsin,2740,2167,5807406
36,West South Central,Oklahoma,2823,1048,3940235
40,South Atlantic,South Carolina,3082,851,5084156
8,South Atlantic,District of Columbia,3770,3134,701547
25,West North Central,Missouri,3776,2107,6121623
14,East North Central,Indiana,3776,1482,6695497
46,South Atlantic,Virginia,3928,2047,8501286
23,West North Central,Minnesota,3993,3250,5606249
11,Pacific,Hawaii,4131,2399,1420593
20,South Atlantic,Maryland,4914,2230,6035802
22,East North Central,Michigan,5209,3142,9984072
30,Mid-Atlantic,New Jersey,6048,3350,8886025
42,East South Central,Tennessee,6139,1744,6771631
33,South Atlantic,North Carolina,6451,2817,10381615
13,East North Central,Illinois,6752,3891,12723071
21,New England,Massachusetts,6811,13257,6882635
35,East North Central,Ohio,6929,3320,11676341
10,South Atlantic,Georgia,6943,2556,10511131
28,Mountain,Nevada,7058,486,3027341
2,Mountain,Arizona,7259,2606,7158024
5,Mountain,Colorado,7607,3250,5691287
38,Mid-Atlantic,Pennsylvania,8163,5349,12800922
37,Pacific,Oregon,11139,3337,4181886
47,Pacific,Washington,16424,5880,7523869
43,West South Central,Texas,19199,6111,28628666
9,South Atlantic,Florida,21443,9587,21244317
32,Mid-Atlantic,New York,39827,52070,19530351
4,Pacific,California,109008,20964,39461588

In [80]:
# Ordena el DataFrame por la columna 'family_members' de forma descendente
homelessness_fam= homelessness.sort_values(by='family_members',ascending=False)

# Imprime el resultado
display(homelessness_fam)

,region,state,individuals,family_members,state_pop
32,Mid-Atlantic,New York,39827,52070,19530351
4,Pacific,California,109008,20964,39461588
21,New England,Massachusetts,6811,13257,6882635
9,South Atlantic,Florida,21443,9587,21244317
43,West South Central,Texas,19199,6111,28628666
47,Pacific,Washington,16424,5880,7523869
38,Mid-Atlantic,Pennsylvania,8163,5349,12800922
13,East North Central,Illinois,6752,3891,12723071
30,Mid-Atlantic,New Jersey,6048,3350,8886025
37,Pacific,Oregon,11139,3337,4181886
35,East North Central,Ohio,6929,3320,11676341
5,Mountain,Colorado,7607,3250,5691287
23,West North Central,Minnesota,3993,3250,5606249
22,East North Central,Michigan,5209,3142,9984072
8,South Atlantic,District of Columbia,3770,3134,701547
33,South Atlantic,North Carolina,6451,2817,10381615
2,Mountain,Arizona,7259,2606,7158024
10,South Atlantic,Georgia,6943,2556,10511131
11,Pacific,Hawaii,4131,2399,1420593
20,South Atlantic,Maryland,4914,2230,6035802
49,East North Central,Wisconsin,2740,2167,5807406
25,West North Central,Missouri,3776,2107,6121623
46,South Atlantic,Virginia,3928,2047,8501286
42,East South Central,Tennessee,6139,1744,6771631
6,New England,Connecticut,2280,1696,3571520
14,East North Central,Indiana,3776,1482,6695497
19,New England,Maine,1450,1066,1339057
36,West South Central,Oklahoma,2823,1048,3940235
15,West North Central,Iowa,1711,1038,3148618
44,Mountain,Utah,1904,972,3153550
17,East South Central,Kentucky,2735,953,4461153
0,East South Central,Alabama,2570,864,4887681
40,South Atlantic,South Carolina,3082,851,5084156
16,West North Central,Kansas,1443,773,2911359
12,Mountain,Idaho,1297,715,1750536
27,West North Central,Nebraska,1745,676,1925614
29,New England,New Hampshire,835,615,1353465
31,Mountain,New Mexico,1949,602,2092741
1,Pacific,Alaska,1434,582,735139
18,West South Central,Louisiana,2540,519,4659690
45,New England,Vermont,780,511,624358
28,Mountain,Nevada,7058,486,3027341
3,West South Central,Arkansas,2280,432,3009733
26,Mountain,Montana,983,422,1060665
7,South Atlantic,Delaware,708,374,965479
39,New England,Rhode Island,747,354,1058287
24,East South Central,Mississippi,1024,328,2981020
41,West North Central,South Dakota,836,323,878698
48,South Atlantic,West Virginia,1021,222,1804291
50,Mountain,Wyoming,434,205,577601
34,West North Central,North Dakota,467,75,758080

In [83]:
# Ordena el DataFrame por la columna 'region' y la columna 'state_pop' de manera descendente y ascendente respectivamente
homelessness_reg_state:state=homelessness.sort_values(by=['region','state'],ascending=[False,True])
# Imprime el resultado
display(homelessness_reg_state)

,region,state,individuals,family_members,state_pop
3,West South Central,Arkansas,2280,432,3009733
18,West South Central,Louisiana,2540,519,4659690
36,West South Central,Oklahoma,2823,1048,3940235
43,West South Central,Texas,19199,6111,28628666
15,West North Central,Iowa,1711,1038,3148618
16,West North Central,Kansas,1443,773,2911359
23,West North Central,Minnesota,3993,3250,5606249
25,West North Central,Missouri,3776,2107,6121623
27,West North Central,Nebraska,1745,676,1925614
34,West North Central,North Dakota,467,75,758080
41,West North Central,South Dakota,836,323,878698
7,South Atlantic,Delaware,708,374,965479
8,South Atlantic,District of Columbia,3770,3134,701547
9,South Atlantic,Florida,21443,9587,21244317
10,South Atlantic,Georgia,6943,2556,10511131
20,South Atlantic,Maryland,4914,2230,6035802
33,South Atlantic,North Carolina,6451,2817,10381615
40,South Atlantic,South Carolina,3082,851,5084156
46,South Atlantic,Virginia,3928,2047,8501286
48,South Atlantic,West Virginia,1021,222,1804291
1,Pacific,Alaska,1434,582,735139
4,Pacific,California,109008,20964,39461588
11,Pacific,Hawaii,4131,2399,1420593
37,Pacific,Oregon,11139,3337,4181886
47,Pacific,Washington,16424,5880,7523869
6,New England,Connecticut,2280,1696,3571520
19,New England,Maine,1450,1066,1339057
21,New England,Massachusetts,6811,13257,6882635
29,New England,New Hampshire,835,615,1353465
39,New England,Rhode Island,747,354,1058287
45,New England,Vermont,780,511,624358
2,Mountain,Arizona,7259,2606,7158024
5,Mountain,Colorado,7607,3250,5691287
12,Mountain,Idaho,1297,715,1750536
26,Mountain,Montana,983,422,1060665
28,Mountain,Nevada,7058,486,3027341
31,Mountain,New Mexico,1949,602,2092741
44,Mountain,Utah,1904,972,3153550
50,Mountain,Wyoming,434,205,577601
30,Mid-Atlantic,New Jersey,6048,3350,8886025
32,Mid-Atlantic,New York,39827,52070,19530351
38,Mid-Atlantic,Pennsylvania,8163,5349,12800922
0,East South Central,Alabama,2570,864,4887681
17,East South Central,Kentucky,2735,953,4461153
24,East South Central,Mississippi,1024,328,2981020
42,East South Central,Tennessee,6139,1744,6771631
13,East North Central,Illinois,6752,3891,12723071
14,East North Central,Indiana,3776,1482,6695497
22,East North Central,Michigan,5209,3142,9984072
35,East North Central,Ohio,6929,3320,11676341
49,East North Central,Wisconsin,2740,2167,5807406

## Seleccionando columnas de un DataFrame
<p>Cuando trabajamos con datos, es posible que no necesitemos todas las variables en nuestro conjunto de datos. Los corchetes (<code>[]</code>) se pueden utilizar para seleccionar solo las columnas que nos interesan en un orden que nos resulte lógico... Para seleccionar solo la columna <code>"col_a"</code> de un DataFrame df, usaremos <code>df["col_a"]</code></p>

In [86]:
# Selecciona la columna 'individuals' 
Individuals=homelessness[['individuals','family_members']]
# Imprime el resultado
display(Individuals)

    individuals  family_members
0          2570             864
1          1434             582
2          7259            2606
3          2280             432
4        109008           20964
5          7607            3250
6          2280            1696
7           708             374
8          3770            3134
9         21443            9587
10         6943            2556
11         4131            2399
12         1297             715
13         6752            3891
14         3776            1482
15         1711            1038
16         1443             773
17         2735             953
18         2540             519
19         1450            1066
20         4914            2230
21         6811           13257
22         5209            3142
23         3993            3250
24         1024             328
25         3776            2107
26          983             422
27         1745             676
28         7058             486
29          835             615
30         6048            3350
31         1949             602
32        39827           52070
33         6451            2817
34          467              75
35         6929            3320
36         2823            1048
37        11139            3337
38         8163            5349
39          747             354
40         3082             851
41          836             323
42         6139            1744
43        19199            6111
44         1904             972
45          780             511
46         3928            2047
47        16424            5880
48         1021             222
49         2740            2167
50          434             205

In [87]:
# Selecciona las columnas 'state' y 'family_members'
Individuals=homelessness[['individuals','family_members']]
# Imprime el resultado
display(Individuals)

    individuals  family_members
0          2570             864
1          1434             582
2          7259            2606
3          2280             432
4        109008           20964
5          7607            3250
6          2280            1696
7           708             374
8          3770            3134
9         21443            9587
10         6943            2556
11         4131            2399
12         1297             715
13         6752            3891
14         3776            1482
15         1711            1038
16         1443             773
17         2735             953
18         2540             519
19         1450            1066
20         4914            2230
21         6811           13257
22         5209            3142
23         3993            3250
24         1024             328
25         3776            2107
26          983             422
27         1745             676
28         7058             486
29          835             615
30         6048            3350
31         1949             602
32        39827           52070
33         6451            2817
34          467              75
35         6929            3320
36         2823            1048
37        11139            3337
38         8163            5349
39          747             354
40         3082             851
41          836             323
42         6139            1744
43        19199            6111
44         1904             972
45          780             511
46         3928            2047
47        16424            5880
48         1021             222
49         2740            2167
50          434             205

In [88]:
# Selecciona las columnas 'region' y 'individuals' y de manera ascendente y descendente respectivamente
reg_ind = homelessness[['region','individuals']].sort_values(by=['region','individuals'], ascending=[True,False])
# Imprime el resultado
display(reg_ind)

                region  individuals
35  East North Central         6929
13  East North Central         6752
22  East North Central         5209
14  East North Central         3776
49  East North Central         2740
42  East South Central         6139
17  East South Central         2735
0   East South Central         2570
24  East South Central         1024
32        Mid-Atlantic        39827
38        Mid-Atlantic         8163
30        Mid-Atlantic         6048
5             Mountain         7607
2             Mountain         7259
28            Mountain         7058
31            Mountain         1949
44            Mountain         1904
12            Mountain         1297
26            Mountain          983
50            Mountain          434
21         New England         6811
6          New England         2280
19         New England         1450
29         New England          835
45         New England          780
39         New England          747
4              Pacific       109008
47             Pacific        16424
37             Pacific        11139
11             Pacific         4131
1              Pacific         1434
9       South Atlantic        21443
10      South Atlantic         6943
33      South Atlantic         6451
20      South Atlantic         4914
46      South Atlantic         3928
8       South Atlantic         3770
40      South Atlantic         3082
48      South Atlantic         1021
7       South Atlantic          708
23  West North Central         3993
25  West North Central         3776
27  West North Central         1745
15  West North Central         1711
16  West North Central         1443
41  West North Central          836
34  West North Central          467
43  West South Central        19199
36  West South Central         2823
18  West South Central         2540
3   West South Central         2280

## Filtrando un DataFrame
<p>Una gran parte del proceso de análisis de datos consiste en encontrar qué partes de un conjunto de datos son interesantes. Una de las técnicas más simples para esto es encontrar un subconjunto de filas que coincida con algunos criterios. Esto a veces se conoce como <i>subsetting rows</i>.</p>

In [90]:
# Filtra las filas donde 'individuals' sea mayor a 10000
homelessness['individuals']>10000
# Resultado

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32     True
33    False
34    False
35    False
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43     True
44    False
45    False
46    False
47     True
48    False
49    False
50    False
Name: individuals, dtype: bool

In [94]:
filtro = homelessness['individuals']>10000
ind_mayores_10K=homelessness[filtro]
display(ind_mayores_10K)

                region       state  individuals  family_members  state_pop
4              Pacific  California       109008           20964   39461588
9       South Atlantic     Florida        21443            9587   21244317
32        Mid-Atlantic    New York        39827           52070   19530351
37             Pacific      Oregon        11139            3337    4181886
43  West South Central       Texas        19199            6111   28628666
47             Pacific  Washington        16424            5880    7523869

In [97]:
# Filra las filas donde 'region' es 'Mountain'
filtro = (homelessness['region']=='Mountain')
mountain_region=homelessness[filtro]
# Resultado
display(mountain_region)

      region       state  individuals  family_members  state_pop
2   Mountain     Arizona         7259            2606    7158024
5   Mountain    Colorado         7607            3250    5691287
12  Mountain       Idaho         1297             715    1750536
26  Mountain     Montana          983             422    1060665
28  Mountain      Nevada         7058             486    3027341
31  Mountain  New Mexico         1949             602    2092741
44  Mountain        Utah         1904             972    3153550
50  Mountain     Wyoming          434             205     577601

In [98]:
# Fltra las filas donde 'family_members' sea menor a '1000' y la region sea 'Pacific'
homelessness_family_region= (homelessness['family_members']<1000)&(homelessness['region']=='Pacific')
fam_reg_filtro=homelessness[homelessness_family_region]
# Resultado
display(fam_reg_filtro)

    region   state  individuals  family_members  state_pop
1  Pacific  Alaska         1434             582     735139

## Filtrando variables categóricas
<p>Filtrar un conjunto de datos basado en una variable categórica a menudo implica el uso del operador "o" (<code>|</code>) para seleccionar filas de varias categorías. Esto puede resultar tedioso cuando, por ejemplo, deseamos que una variable cumpla tres o más condiciones. Para esto, podemos utilizar el método <code>.isin()</code> que nos permitirá abordar este problema escribiendo una condición en lugar de tres o más por separado.</p>

In [100]:
# Filtra las filas que contengan las regiones South Atlantic o Mid-Atlantic
filtro = homelessness['region'].isin(['South Atlantic','Mid-Atlantic'])
# Resultado
filtro_variables= homelessness[filtro]
display(filtro_variables)

,region,state,individuals,family_members,state_pop
7,South Atlantic,Delaware,708,374,965479
8,South Atlantic,District of Columbia,3770,3134,701547
9,South Atlantic,Florida,21443,9587,21244317
10,South Atlantic,Georgia,6943,2556,10511131
20,South Atlantic,Maryland,4914,2230,6035802
30,Mid-Atlantic,New Jersey,6048,3350,8886025
32,Mid-Atlantic,New York,39827,52070,19530351
33,South Atlantic,North Carolina,6451,2817,10381615
38,Mid-Atlantic,Pennsylvania,8163,5349,12800922
40,South Atlantic,South Carolina,3082,851,5084156
46,South Atlantic,Virginia,3928,2047,8501286
48,South Atlantic,West Virginia,1021,222,1804291

In [103]:
# Estados donde hay desiertos
Desiertos = ['California','Arizona','Nevada','Utah']
# Filtra las filas con los estados en donde hay desiertos
filtro= (homelessness['state'].isin(Desiertos))
filtro_homelessness= homelessness[filtro]
# Resultado
display(filtro_homelessness)

      region       state  individuals  family_members  state_pop
2   Mountain     Arizona         7259            2606    7158024
4    Pacific  California       109008           20964   39461588
28  Mountain      Nevada         7058             486    3027341
44  Mountain        Utah         1904             972    3153550

## Agregando nuevas columnas
<p>Por lo general los datos que tenemos no son suficientes para nuestro análisis, siempre necesitamos agregar nuevas columnas o campos calculados a nuestro DataFrame. Esto en el campo de la ciencia de datos se le conoce como <i>feature engineering</i>.
Se pueden crear nuevas columnas desde cero, pero también es común derivarlas de otras, por ejemplo, agregando campos calculados con base en otro existente o cambiando su escala de unidades o valor.
    
En este ejercicio, vamos a contestar la pregunta: "¿Qué estado tiene el mayor número de personas sin hogar por cada 10,000 personas?
</p>

In [114]:
#Crear una columna nueva 
homelessness['columna nueva']=1
display(homelessness)

,region,state,individuals,family_members,state_pop,columna nueva,total_homelessness
0,East South Central,Alabama,2570,864,4887681,1,3434
1,Pacific,Alaska,1434,582,735139,1,2016
2,Mountain,Arizona,7259,2606,7158024,1,9865
3,West South Central,Arkansas,2280,432,3009733,1,2712
4,Pacific,California,109008,20964,39461588,1,129972
5,Mountain,Colorado,7607,3250,5691287,1,10857
6,New England,Connecticut,2280,1696,3571520,1,3976
7,South Atlantic,Delaware,708,374,965479,1,1082
8,South Atlantic,District of Columbia,3770,3134,701547,1,6904
9,South Atlantic,Florida,21443,9587,21244317,1,31030
10,South Atlantic,Georgia,6943,2556,10511131,1,9499
11,Pacific,Hawaii,4131,2399,1420593,1,6530
12,Mountain,Idaho,1297,715,1750536,1,2012
13,East North Central,Illinois,6752,3891,12723071,1,10643
14,East North Central,Indiana,3776,1482,6695497,1,5258
15,West North Central,Iowa,1711,1038,3148618,1,2749
16,West North Central,Kansas,1443,773,2911359,1,2216
17,East South Central,Kentucky,2735,953,4461153,1,3688
18,West South Central,Louisiana,2540,519,4659690,1,3059
19,New England,Maine,1450,1066,1339057,1,2516
20,South Atlantic,Maryland,4914,2230,6035802,1,7144
21,New England,Massachusetts,6811,13257,6882635,1,20068
22,East North Central,Michigan,5209,3142,9984072,1,8351
23,West North Central,Minnesota,3993,3250,5606249,1,7243
24,East South Central,Mississippi,1024,328,2981020,1,1352
25,West North Central,Missouri,3776,2107,6121623,1,5883
26,Mountain,Montana,983,422,1060665,1,1405
27,West North Central,Nebraska,1745,676,1925614,1,2421
28,Mountain,Nevada,7058,486,3027341,1,7544
29,New England,New Hampshire,835,615,1353465,1,1450
30,Mid-Atlantic,New Jersey,6048,3350,8886025,1,9398
31,Mountain,New Mexico,1949,602,2092741,1,2551
32,Mid-Atlantic,New York,39827,52070,19530351,1,91897
33,South Atlantic,North Carolina,6451,2817,10381615,1,9268
34,West North Central,North Dakota,467,75,758080,1,542
35,East North Central,Ohio,6929,3320,11676341,1,10249
36,West South Central,Oklahoma,2823,1048,3940235,1,3871
37,Pacific,Oregon,11139,3337,4181886,1,14476
38,Mid-Atlantic,Pennsylvania,8163,5349,12800922,1,13512
39,New England,Rhode Island,747,354,1058287,1,1101
40,South Atlantic,South Carolina,3082,851,5084156,1,3933
41,West North Central,South Dakota,836,323,878698,1,1159
42,East South Central,Tennessee,6139,1744,6771631,1,7883
43,West South Central,Texas,19199,6111,28628666,1,25310
44,Mountain,Utah,1904,972,3153550,1,2876
45,New England,Vermont,780,511,624358,1,1291
46,South Atlantic,Virginia,3928,2047,8501286,1,5975
47,Pacific,Washington,16424,5880,7523869,1,22304
48,South Atlantic,West Virginia,1021,222,1804291,1,1243
49,East North Central,Wisconsin,2740,2167,5807406,1,4907
50,Mountain,Wyoming,434,205,577601,1,639

In [ ]:
# Agregamos una columna que tenga el total de columnas sin hogar
homelessness['total_homelessness'] = homelessness['individuals'] + homelessness['family_members']
display(homelessness)
# Crear una columna que calcule las personas sin hogar por cada 10K personas por estado
homelessness['indiv_per_20k']=homelessness['homelessness_per_capita']*10000
display(homelessness)
# Vamos a filtrar esta nueva columna 'indiv_per_20k' con valores mayores a 20
homelessness[homelessness['indiv_per_20k']>20]
display(homelessness)
# Resultado

,region,state,individuals,family_members,state_pop,columna nueva,total_homelessness,homelessness_per_capita,indiv_per_20k
0,East South Central,Alabama,2570,864,4887681,1,3434,0.000703,7.025827
1,Pacific,Alaska,1434,582,735139,1,2016,0.002742,27.423385
2,Mountain,Arizona,7259,2606,7158024,1,9865,0.001378,13.781736
3,West South Central,Arkansas,2280,432,3009733,1,2712,0.000901,9.010766
4,Pacific,California,109008,20964,39461588,1,129972,0.003294,32.936333
5,Mountain,Colorado,7607,3250,5691287,1,10857,0.001908,19.076529
6,New England,Connecticut,2280,1696,3571520,1,3976,0.001113,11.132515
7,South Atlantic,Delaware,708,374,965479,1,1082,0.001121,11.206872
8,South Atlantic,District of Columbia,3770,3134,701547,1,6904,0.009841,98.411083
9,South Atlantic,Florida,21443,9587,21244317,1,31030,0.001461,14.606259
10,South Atlantic,Georgia,6943,2556,10511131,1,9499,0.000904,9.037086
11,Pacific,Hawaii,4131,2399,1420593,1,6530,0.004597,45.966720
12,Mountain,Idaho,1297,715,1750536,1,2012,0.001149,11.493623
13,East North Central,Illinois,6752,3891,12723071,1,10643,0.000837,8.365119
14,East North Central,Indiana,3776,1482,6695497,1,5258,0.000785,7.853039
15,West North Central,Iowa,1711,1038,3148618,1,2749,0.000873,8.730815
16,West North Central,Kansas,1443,773,2911359,1,2216,0.000761,7.611566
17,East South Central,Kentucky,2735,953,4461153,1,3688,0.000827,8.266921
18,West South Central,Louisiana,2540,519,4659690,1,3059,0.000656,6.564814
19,New England,Maine,1450,1066,1339057,1,2516,0.001879,18.789342
20,South Atlantic,Maryland,4914,2230,6035802,1,7144,0.001184,11.836041
21,New England,Massachusetts,6811,13257,6882635,1,20068,0.002916,29.157438
22,East North Central,Michigan,5209,3142,9984072,1,8351,0.000836,8.364323
23,West North Central,Minnesota,3993,3250,5606249,1,7243,0.001292,12.919512
24,East South Central,Mississippi,1024,328,2981020,1,1352,0.000454,4.535360
25,West North Central,Missouri,3776,2107,6121623,1,5883,0.000961,9.610197
26,Mountain,Montana,983,422,1060665,1,1405,0.001325,13.246407
27,West North Central,Nebraska,1745,676,1925614,1,2421,0.001257,12.572613
28,Mountain,Nevada,7058,486,3027341,1,7544,0.002492,24.919558
29,New England,New Hampshire,835,615,1353465,1,1450,0.001071,10.713243
30,Mid-Atlantic,New Jersey,6048,3350,8886025,1,9398,0.001058,10.576158
31,Mountain,New Mexico,1949,602,2092741,1,2551,0.001219,12.189755
32,Mid-Atlantic,New York,39827,52070,19530351,1,91897,0.004705,47.053430
33,South Atlantic,North Carolina,6451,2817,10381615,1,9268,0.000893,8.927320
34,West North Central,North Dakota,467,75,758080,1,542,0.000715,7.149641
35,East North Central,Ohio,6929,3320,11676341,1,10249,0.000878,8.777579
36,West South Central,Oklahoma,2823,1048,3940235,1,3871,0.000982,9.824287
37,Pacific,Oregon,11139,3337,4181886,1,14476,0.003462,34.615960
38,Mid-Atlantic,Pennsylvania,8163,5349,12800922,1,13512,0.001056,10.555490
39,New England,Rhode Island,747,354,1058287,1,1101,0.001040,10.403605
40,South Atlantic,South Carolina,3082,851,5084156,1,3933,0.000774,7.735797
41,West North Central,South Dakota,836,323,878698,1,1159,0.001319,13.189970
42,East South Central,Tennessee,6139,1744,6771631,1,7883,0.001164,11.641213
43,West South Central,Texas,19199,6111,28628666,1,25310,0.000884,8.840789
44,Mountain,Utah,1904,972,3153550,1,2876,0.000912,9.119881
45,New England,Vermont,780,511,624358,1,1291,0.002068,20.677240
46,South Atlantic,Virginia,3928,2047,8501286,1,5975,0.000703,7.028348
47,Pacific,Washington,16424,5880,7523869,1,22304,0.002964,29.644323
48,South Atlantic,West Virginia,1021,222,1804291,1,1243,0.000689,6.889133
49,East North Central,Wisconsin,2740,2167,5807406,1,4907,0.000845,8.449556
50,Mountain,Wyoming,434,205,577601,1,639,0.001106,11.063000

,region,state,individuals,family_members,state_pop,columna nueva,total_homelessness,homelessness_per_capita,indiv_per_20k
0,East South Central,Alabama,2570,864,4887681,1,3434,0.000703,7.025827
1,Pacific,Alaska,1434,582,735139,1,2016,0.002742,27.423385
2,Mountain,Arizona,7259,2606,7158024,1,9865,0.001378,13.781736
3,West South Central,Arkansas,2280,432,3009733,1,2712,0.000901,9.010766
4,Pacific,California,109008,20964,39461588,1,129972,0.003294,32.936333
5,Mountain,Colorado,7607,3250,5691287,1,10857,0.001908,19.076529
6,New England,Connecticut,2280,1696,3571520,1,3976,0.001113,11.132515
7,South Atlantic,Delaware,708,374,965479,1,1082,0.001121,11.206872
8,South Atlantic,District of Columbia,3770,3134,701547,1,6904,0.009841,98.411083
9,South Atlantic,Florida,21443,9587,21244317,1,31030,0.001461,14.606259
10,South Atlantic,Georgia,6943,2556,10511131,1,9499,0.000904,9.037086
11,Pacific,Hawaii,4131,2399,1420593,1,6530,0.004597,45.966720
12,Mountain,Idaho,1297,715,1750536,1,2012,0.001149,11.493623
13,East North Central,Illinois,6752,3891,12723071,1,10643,0.000837,8.365119
14,East North Central,Indiana,3776,1482,6695497,1,5258,0.000785,7.853039
15,West North Central,Iowa,1711,1038,3148618,1,2749,0.000873,8.730815
16,West North Central,Kansas,1443,773,2911359,1,2216,0.000761,7.611566
17,East South Central,Kentucky,2735,953,4461153,1,3688,0.000827,8.266921
18,West South Central,Louisiana,2540,519,4659690,1,3059,0.000656,6.564814
19,New England,Maine,1450,1066,1339057,1,2516,0.001879,18.789342
20,South Atlantic,Maryland,4914,2230,6035802,1,7144,0.001184,11.836041
21,New England,Massachusetts,6811,13257,6882635,1,20068,0.002916,29.157438
22,East North Central,Michigan,5209,3142,9984072,1,8351,0.000836,8.364323
23,West North Central,Minnesota,3993,3250,5606249,1,7243,0.001292,12.919512
24,East South Central,Mississippi,1024,328,2981020,1,1352,0.000454,4.535360
25,West North Central,Missouri,3776,2107,6121623,1,5883,0.000961,9.610197
26,Mountain,Montana,983,422,1060665,1,1405,0.001325,13.246407
27,West North Central,Nebraska,1745,676,1925614,1,2421,0.001257,12.572613
28,Mountain,Nevada,7058,486,3027341,1,7544,0.002492,24.919558
29,New England,New Hampshire,835,615,1353465,1,1450,0.001071,10.713243
30,Mid-Atlantic,New Jersey,6048,3350,8886025,1,9398,0.001058,10.576158
31,Mountain,New Mexico,1949,602,2092741,1,2551,0.001219,12.189755
32,Mid-Atlantic,New York,39827,52070,19530351,1,91897,0.004705,47.053430
33,South Atlantic,North Carolina,6451,2817,10381615,1,9268,0.000893,8.927320
34,West North Central,North Dakota,467,75,758080,1,542,0.000715,7.149641
35,East North Central,Ohio,6929,3320,11676341,1,10249,0.000878,8.777579
36,West South Central,Oklahoma,2823,1048,3940235,1,3871,0.000982,9.824287
37,Pacific,Oregon,11139,3337,4181886,1,14476,0.003462,34.615960
38,Mid-Atlantic,Pennsylvania,8163,5349,12800922,1,13512,0.001056,10.555490
39,New England,Rhode Island,747,354,1058287,1,1101,0.001040,10.403605
40,South Atlantic,South Carolina,3082,851,5084156,1,3933,0.000774,7.735797
41,West North Central,South Dakota,836,323,878698,1,1159,0.001319,13.189970
42,East South Central,Tennessee,6139,1744,6771631,1,7883,0.001164,11.641213
43,West South Central,Texas,19199,6111,28628666,1,25310,0.000884,8.840789
44,Mountain,Utah,1904,972,3153550,1,2876,0.000912,9.119881
45,New England,Vermont,780,511,624358,1,1291,0.002068,20.677240
46,South Atlantic,Virginia,3928,2047,8501286,1,5975,0.000703,7.028348
47,Pacific,Washington,16424,5880,7523869,1,22304,0.002964,29.644323
48,South Atlantic,West Virginia,1021,222,1804291,1,1243,0.000689,6.889133
49,East North Central,Wisconsin,2740,2167,5807406,1,4907,0.000845,8.449556
50,Mountain,Wyoming,434,205,577601,1,639,0.001106,11.063000

,region,state,individuals,family_members,state_pop,columna nueva,total_homelessness,homelessness_per_capita,indiv_per_20k
0,East South Central,Alabama,2570,864,4887681,1,3434,0.000703,7.025827
1,Pacific,Alaska,1434,582,735139,1,2016,0.002742,27.423385
2,Mountain,Arizona,7259,2606,7158024,1,9865,0.001378,13.781736
3,West South Central,Arkansas,2280,432,3009733,1,2712,0.000901,9.010766
4,Pacific,California,109008,20964,39461588,1,129972,0.003294,32.936333
5,Mountain,Colorado,7607,3250,5691287,1,10857,0.001908,19.076529
6,New England,Connecticut,2280,1696,3571520,1,3976,0.001113,11.132515
7,South Atlantic,Delaware,708,374,965479,1,1082,0.001121,11.206872
8,South Atlantic,District of Columbia,3770,3134,701547,1,6904,0.009841,98.411083
9,South Atlantic,Florida,21443,9587,21244317,1,31030,0.001461,14.606259
10,South Atlantic,Georgia,6943,2556,10511131,1,9499,0.000904,9.037086
11,Pacific,Hawaii,4131,2399,1420593,1,6530,0.004597,45.966720
12,Mountain,Idaho,1297,715,1750536,1,2012,0.001149,11.493623
13,East North Central,Illinois,6752,3891,12723071,1,10643,0.000837,8.365119
14,East North Central,Indiana,3776,1482,6695497,1,5258,0.000785,7.853039
15,West North Central,Iowa,1711,1038,3148618,1,2749,0.000873,8.730815
16,West North Central,Kansas,1443,773,2911359,1,2216,0.000761,7.611566
17,East South Central,Kentucky,2735,953,4461153,1,3688,0.000827,8.266921
18,West South Central,Louisiana,2540,519,4659690,1,3059,0.000656,6.564814
19,New England,Maine,1450,1066,1339057,1,2516,0.001879,18.789342
20,South Atlantic,Maryland,4914,2230,6035802,1,7144,0.001184,11.836041
21,New England,Massachusetts,6811,13257,6882635,1,20068,0.002916,29.157438
22,East North Central,Michigan,5209,3142,9984072,1,8351,0.000836,8.364323
23,West North Central,Minnesota,3993,3250,5606249,1,7243,0.001292,12.919512
24,East South Central,Mississippi,1024,328,2981020,1,1352,0.000454,4.535360
25,West North Central,Missouri,3776,2107,6121623,1,5883,0.000961,9.610197
26,Mountain,Montana,983,422,1060665,1,1405,0.001325,13.246407
27,West North Central,Nebraska,1745,676,1925614,1,2421,0.001257,12.572613
28,Mountain,Nevada,7058,486,3027341,1,7544,0.002492,24.919558
29,New England,New Hampshire,835,615,1353465,1,1450,0.001071,10.713243
30,Mid-Atlantic,New Jersey,6048,3350,8886025,1,9398,0.001058,10.576158
31,Mountain,New Mexico,1949,602,2092741,1,2551,0.001219,12.189755
32,Mid-Atlantic,New York,39827,52070,19530351,1,91897,0.004705,47.053430
33,South Atlantic,North Carolina,6451,2817,10381615,1,9268,0.000893,8.927320
34,West North Central,North Dakota,467,75,758080,1,542,0.000715,7.149641
35,East North Central,Ohio,6929,3320,11676341,1,10249,0.000878,8.777579
36,West South Central,Oklahoma,2823,1048,3940235,1,3871,0.000982,9.824287
37,Pacific,Oregon,11139,3337,4181886,1,14476,0.003462,34.615960
38,Mid-Atlantic,Pennsylvania,8163,5349,12800922,1,13512,0.001056,10.555490
39,New England,Rhode Island,747,354,1058287,1,1101,0.001040,10.403605
40,South Atlantic,South Carolina,3082,851,5084156,1,3933,0.000774,7.735797
41,West North Central,South Dakota,836,323,878698,1,1159,0.001319,13.189970
42,East South Central,Tennessee,6139,1744,6771631,1,7883,0.001164,11.641213
43,West South Central,Texas,19199,6111,28628666,1,25310,0.000884,8.840789
44,Mountain,Utah,1904,972,3153550,1,2876,0.000912,9.119881
45,New England,Vermont,780,511,624358,1,1291,0.002068,20.677240
46,South Atlantic,Virginia,3928,2047,8501286,1,5975,0.000703,7.028348
47,Pacific,Washington,16424,5880,7523869,1,22304,0.002964,29.644323
48,South Atlantic,West Virginia,1021,222,1804291,1,1243,0.000689,6.889133
49,East North Central,Wisconsin,2740,2167,5807406,1,4907,0.000845,8.449556
50,Mountain,Wyoming,434,205,577601,1,639,0.001106,11.063000

In [134]:
# Vamos a filtrar esta nueva columna 'indiv_per_20k' con valores mayores a 20
filtro = homelessness['indiv_per_20k']>20
homelessness_filtro= homelessness[filtro]
display(homelessness_filtro)

,region,state,individuals,family_members,state_pop,columna nueva,total_homelessness,homelessness_per_capita,indiv_per_20k
1,Pacific,Alaska,1434,582,735139,1,2016,0.002742,27.423385
4,Pacific,California,109008,20964,39461588,1,129972,0.003294,32.936333
8,South Atlantic,District of Columbia,3770,3134,701547,1,6904,0.009841,98.411083
11,Pacific,Hawaii,4131,2399,1420593,1,6530,0.004597,45.966720
21,New England,Massachusetts,6811,13257,6882635,1,20068,0.002916,29.157438
28,Mountain,Nevada,7058,486,3027341,1,7544,0.002492,24.919558
32,Mid-Atlantic,New York,39827,52070,19530351,1,91897,0.004705,47.053430
37,Pacific,Oregon,11139,3337,4181886,1,14476,0.003462,34.615960
45,New England,Vermont,780,511,624358,1,1291,0.002068,20.677240
47,Pacific,Washington,16424,5880,7523869,1,22304,0.002964,29.644323

In [127]:
# Vamos a ordenar de mandera descendente nuestra nueva variable
homelessness_ordenada=homelessness.sort_values(by='indiv_per_20k',ascending=False)
display(homelessness_ordenada)

,region,state,individuals,family_members,state_pop,columna nueva,total_homelessness,homelessness_per_capita,indiv_per_20k
8,South Atlantic,District of Columbia,3770,3134,701547,1,6904,0.009841,98.411083
32,Mid-Atlantic,New York,39827,52070,19530351,1,91897,0.004705,47.053430
11,Pacific,Hawaii,4131,2399,1420593,1,6530,0.004597,45.966720
37,Pacific,Oregon,11139,3337,4181886,1,14476,0.003462,34.615960
4,Pacific,California,109008,20964,39461588,1,129972,0.003294,32.936333
47,Pacific,Washington,16424,5880,7523869,1,22304,0.002964,29.644323
21,New England,Massachusetts,6811,13257,6882635,1,20068,0.002916,29.157438
1,Pacific,Alaska,1434,582,735139,1,2016,0.002742,27.423385
28,Mountain,Nevada,7058,486,3027341,1,7544,0.002492,24.919558
45,New England,Vermont,780,511,624358,1,1291,0.002068,20.677240
5,Mountain,Colorado,7607,3250,5691287,1,10857,0.001908,19.076529
19,New England,Maine,1450,1066,1339057,1,2516,0.001879,18.789342
9,South Atlantic,Florida,21443,9587,21244317,1,31030,0.001461,14.606259
2,Mountain,Arizona,7259,2606,7158024,1,9865,0.001378,13.781736
26,Mountain,Montana,983,422,1060665,1,1405,0.001325,13.246407
41,West North Central,South Dakota,836,323,878698,1,1159,0.001319,13.189970
23,West North Central,Minnesota,3993,3250,5606249,1,7243,0.001292,12.919512
27,West North Central,Nebraska,1745,676,1925614,1,2421,0.001257,12.572613
31,Mountain,New Mexico,1949,602,2092741,1,2551,0.001219,12.189755
20,South Atlantic,Maryland,4914,2230,6035802,1,7144,0.001184,11.836041
42,East South Central,Tennessee,6139,1744,6771631,1,7883,0.001164,11.641213
12,Mountain,Idaho,1297,715,1750536,1,2012,0.001149,11.493623
7,South Atlantic,Delaware,708,374,965479,1,1082,0.001121,11.206872
6,New England,Connecticut,2280,1696,3571520,1,3976,0.001113,11.132515
50,Mountain,Wyoming,434,205,577601,1,639,0.001106,11.063000
29,New England,New Hampshire,835,615,1353465,1,1450,0.001071,10.713243
30,Mid-Atlantic,New Jersey,6048,3350,8886025,1,9398,0.001058,10.576158
38,Mid-Atlantic,Pennsylvania,8163,5349,12800922,1,13512,0.001056,10.555490
39,New England,Rhode Island,747,354,1058287,1,1101,0.001040,10.403605
36,West South Central,Oklahoma,2823,1048,3940235,1,3871,0.000982,9.824287
25,West North Central,Missouri,3776,2107,6121623,1,5883,0.000961,9.610197
44,Mountain,Utah,1904,972,3153550,1,2876,0.000912,9.119881
10,South Atlantic,Georgia,6943,2556,10511131,1,9499,0.000904,9.037086
3,West South Central,Arkansas,2280,432,3009733,1,2712,0.000901,9.010766
33,South Atlantic,North Carolina,6451,2817,10381615,1,9268,0.000893,8.927320
43,West South Central,Texas,19199,6111,28628666,1,25310,0.000884,8.840789
35,East North Central,Ohio,6929,3320,11676341,1,10249,0.000878,8.777579
15,West North Central,Iowa,1711,1038,3148618,1,2749,0.000873,8.730815
49,East North Central,Wisconsin,2740,2167,5807406,1,4907,0.000845,8.449556
13,East North Central,Illinois,6752,3891,12723071,1,10643,0.000837,8.365119
22,East North Central,Michigan,5209,3142,9984072,1,8351,0.000836,8.364323
17,East South Central,Kentucky,2735,953,4461153,1,3688,0.000827,8.266921
14,East North Central,Indiana,3776,1482,6695497,1,5258,0.000785,7.853039
40,South Atlantic,South Carolina,3082,851,5084156,1,3933,0.000774,7.735797
16,West North Central,Kansas,1443,773,2911359,1,2216,0.000761,7.611566
34,West North Central,North Dakota,467,75,758080,1,542,0.000715,7.149641
46,South Atlantic,Virginia,3928,2047,8501286,1,5975,0.000703,7.028348
0,East South Central,Alabama,2570,864,4887681,1,3434,0.000703,7.025827
48,South Atlantic,West Virginia,1021,222,1804291,1,1243,0.000689,6.889133
18,West South Central,Louisiana,2540,519,4659690,1,3059,0.000656,6.564814
24,East South Central,Mississippi,1024,328,2981020,1,1352,0.000454,4.535360

In [117]:
# Agregamos columnas d epersonas sin hogar per capita
homelessness['homelessness_per_capita'] = homelessness['total_homelessness'] / homelessness['state_pop']

In [118]:
display(homelessness)

,region,state,individuals,family_members,state_pop,columna nueva,total_homelessness,homelessness_per_capita
0,East South Central,Alabama,2570,864,4887681,1,3434,0.000703
1,Pacific,Alaska,1434,582,735139,1,2016,0.002742
2,Mountain,Arizona,7259,2606,7158024,1,9865,0.001378
3,West South Central,Arkansas,2280,432,3009733,1,2712,0.000901
4,Pacific,California,109008,20964,39461588,1,129972,0.003294
5,Mountain,Colorado,7607,3250,5691287,1,10857,0.001908
6,New England,Connecticut,2280,1696,3571520,1,3976,0.001113
7,South Atlantic,Delaware,708,374,965479,1,1082,0.001121
8,South Atlantic,District of Columbia,3770,3134,701547,1,6904,0.009841
9,South Atlantic,Florida,21443,9587,21244317,1,31030,0.001461
10,South Atlantic,Georgia,6943,2556,10511131,1,9499,0.000904
11,Pacific,Hawaii,4131,2399,1420593,1,6530,0.004597
12,Mountain,Idaho,1297,715,1750536,1,2012,0.001149
13,East North Central,Illinois,6752,3891,12723071,1,10643,0.000837
14,East North Central,Indiana,3776,1482,6695497,1,5258,0.000785
15,West North Central,Iowa,1711,1038,3148618,1,2749,0.000873
16,West North Central,Kansas,1443,773,2911359,1,2216,0.000761
17,East South Central,Kentucky,2735,953,4461153,1,3688,0.000827
18,West South Central,Louisiana,2540,519,4659690,1,3059,0.000656
19,New England,Maine,1450,1066,1339057,1,2516,0.001879
20,South Atlantic,Maryland,4914,2230,6035802,1,7144,0.001184
21,New England,Massachusetts,6811,13257,6882635,1,20068,0.002916
22,East North Central,Michigan,5209,3142,9984072,1,8351,0.000836
23,West North Central,Minnesota,3993,3250,5606249,1,7243,0.001292
24,East South Central,Mississippi,1024,328,2981020,1,1352,0.000454
25,West North Central,Missouri,3776,2107,6121623,1,5883,0.000961
26,Mountain,Montana,983,422,1060665,1,1405,0.001325
27,West North Central,Nebraska,1745,676,1925614,1,2421,0.001257
28,Mountain,Nevada,7058,486,3027341,1,7544,0.002492
29,New England,New Hampshire,835,615,1353465,1,1450,0.001071
30,Mid-Atlantic,New Jersey,6048,3350,8886025,1,9398,0.001058
31,Mountain,New Mexico,1949,602,2092741,1,2551,0.001219
32,Mid-Atlantic,New York,39827,52070,19530351,1,91897,0.004705
33,South Atlantic,North Carolina,6451,2817,10381615,1,9268,0.000893
34,West North Central,North Dakota,467,75,758080,1,542,0.000715
35,East North Central,Ohio,6929,3320,11676341,1,10249,0.000878
36,West South Central,Oklahoma,2823,1048,3940235,1,3871,0.000982
37,Pacific,Oregon,11139,3337,4181886,1,14476,0.003462
38,Mid-Atlantic,Pennsylvania,8163,5349,12800922,1,13512,0.001056
39,New England,Rhode Island,747,354,1058287,1,1101,0.001040
40,South Atlantic,South Carolina,3082,851,5084156,1,3933,0.000774
41,West North Central,South Dakota,836,323,878698,1,1159,0.001319
42,East South Central,Tennessee,6139,1744,6771631,1,7883,0.001164
43,West South Central,Texas,19199,6111,28628666,1,25310,0.000884
44,Mountain,Utah,1904,972,3153550,1,2876,0.000912
45,New England,Vermont,780,511,624358,1,1291,0.002068
46,South Atlantic,Virginia,3928,2047,8501286,1,5975,0.000703
47,Pacific,Washington,16424,5880,7523869,1,22304,0.002964
48,South Atlantic,West Virginia,1021,222,1804291,1,1243,0.000689
49,East North Central,Wisconsin,2740,2167,5807406,1,4907,0.000845
50,Mountain,Wyoming,434,205,577601,1,639,0.001106

In [140]:
# Vamos a seleccionar únicamente los campos 'state' y 'indiv_per_20k'
homelessness_filtro = homelessness_filtro[['state','indiv_per_20k']]
display(homelessness_filtro)

                   state  indiv_per_20k
1                 Alaska      27.423385
4             California      32.936333
8   District of Columbia      98.411083
11                Hawaii      45.966720
21         Massachusetts      29.157438
28                Nevada      24.919558
32              New York      47.053430
37                Oregon      34.615960
45               Vermont      20.677240
47            Washington      29.644323