# <span style='color:black'> <center>Manejo de datos con Pandas</center> </span>
## 2. Análisis estadístico y agrupación
<p><img src="https://online.york.ac.uk/wp-content/uploads/2021/07/man-in-a-suit-standing-behind-a-hologram-of-data-analytics-1030x579.jpg" width="750"</p>

## Funciones estadísticas
<p>A través de la estadística tenemos disponible una serie de medidas cuantitativas que nos permiten visualizar el comportamiento de una variable. Como ejemplo tenemos la media, mediana, mínimo, máxima y desviación estándar son estadísticas de resumen. El cálculo de estas nos permite tener una mejor comprensión y entendimiento de nuestro conjunto de datos, incluso si es muy grande.</p>

In [3]:
# Importar pandas y numpy
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# Importar el archivo csv sales a un DataFrame
df = pd.read_csv('C:\\Users\\usuario\\OneDrive\\Escritorio\\Python repositorios\\python-basics\\Data excel para manejo de librería Pandas\\sales.csv')

In [5]:
# Imprimir las primeras 5 lineas de mi DataFrame
display(df.head(5))

,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,1,A,1,05/02/2018,24924.50,False,5.727778,0.679451,8.106
1,1,C,1,05/03/2018,21827.90,False,8.055556,0.693452,8.106
2,1,A,1,02/04/2018,57258.43,False,16.816667,0.718284,7.808
3,1,A,1,07/05/2018,17413.94,False,22.527778,0.748928,7.808
4,1,A,1,04/06/2018,17558.09,False,27.050000,0.714586,7.808

In [6]:
# Imprimr la informacion de los campos de mi DataFrame
df.size
df.shape
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10774 entries, 0 to 10773
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   store                 10774 non-null  int64
 1   type                  10774 non-null  str
 2   department            10774 non-null  int64
 3   date                  10774 non-null  str
 4   weekly_sales          10774 non-null  float64
 5   is_holiday            10774 non-null  bool
 6   temperature_c         10774 non-null  float64
 7   fuel_price_usd_per_l  10774 non-null  float64
 8   unemployment          10774 non-null  float64
dtypes: bool(1), float64(4), int64(2), str(2)
memory usage: 799.8 KB

In [8]:
# Calcular el promedio de las venta semanales
np.mean(df['weekly_sales'])
df['weekly_sales'].mean()

np.float64(23843.95014850566)

In [9]:
# Calcular la mediana de las ventas semanales
np.median(df['weekly_sales'])
df['weekly_sales'].median()

np.float64(12049.064999999999)

In [10]:
#Cambiamos a formato de fecha
df['date'] = pd.to_datetime(df['date'], format= '%d/%m/%Y')
df['date'] = pd.to_datetime(df['date'], dayfirst=True)

In [11]:
# Calcular la última fecha de venta 
df['date'].max()

Timestamp('2020-10-26 00:00:00')

In [12]:
# Calcular la fecha en la que tuve mi primer venta
df['date'].min()

Timestamp('2018-02-05 00:00:00')

## Multiples funciones
<p>El método <code>.agg()</code> nos permite aplicar nuestras propias funciones personalizadas a un DataFrame, así como también aplicar funciones a más de una columna a la vez, lo que hace que los cálculos sean súper eficientes. Lo anterior se hace usando la siguiente nomenclatura: <code>df['columna'].agg([funcion1, funcion2])</code>
    
En la función personalizada para este ejercicio, <code>IQR</code> nos muestra el rango intercuartil, que es el percentil 75 menos el percentil 25. Es una alternativa a la desviación estándar que resulta útil si sus datos contienen valores atípicos.</p>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Boxplot_vs_PDF.svg/1200px-Boxplot_vs_PDF.svg.png" width="450">

In [13]:
# Ejecuta primero las celdas de importación y carga de datos
df = pd.read_csv(r'C:\Users\usuario\OneDrive\Escritorio\Python repositorios\python-basics\Data excel para manejo de librería Pandas\sales.csv')
df[['weekly_sales','temperature_c']].agg(['mean','median','min','max',np.median])

         weekly_sales  temperature_c
mean     23843.950149      15.731978
median   12049.065000      16.966667
min      -1098.000000      -8.366667
max     293966.050000      33.827778
median   12049.065000      16.966667

In [14]:
# Funcion IQR
def iqr(datos):
    calculo= datos.quantile(0.75) - datos.quantile(0.25)
    return calculo

# Calcular el IQR de la columna 'temperature_c' 
display(iqr(df['temperature_c']))

np.float64(16.583333337000003)

In [15]:
##Límite máximo
q3= df['temperature_c'].quantile(0.75)
q1=df['temperature_c'].quantile(0.25)
display(q3)
print(iqr(df['temperature_c']))
print(q3+1.5*iqr(df['temperature_c']))

np.float64(24.16666667)

16.583333337000003
49.04166667550001

In [16]:
# Calcula el IQR para 'temperature_c', 'fuel_price_usd_per_l', y 'unemployment'
df[['temperature_c','fuel_price_usd_per_l','unemployment']].agg(iqr)

temperature_c           16.583333
fuel_price_usd_per_l     0.073176
unemployment             0.565000
dtype: float64

In [17]:
# Agrega el promedio al cálculo anterior
df[['temperature_c', 'fuel_price_usd_per_l', 'unemployment']].agg([iqr, 'mean'])

      temperature_c  fuel_price_usd_per_l  unemployment
iqr       16.583333              0.073176      0.565000
mean      15.731978              0.749746      8.082009

In [18]:
# Crea un nuevo DataFrame que contenga las ventas de la tienda 1 y el departamento 1
display(df)

,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,1,A,1,05/02/2018,24924.50,False,5.727778,0.679451,8.106
1,1,C,1,05/03/2018,21827.90,False,8.055556,0.693452,8.106
2,1,A,1,02/04/2018,57258.43,False,16.816667,0.718284,7.808
3,1,A,1,07/05/2018,17413.94,False,22.527778,0.748928,7.808
4,1,A,1,04/06/2018,17558.09,False,27.050000,0.714586,7.808
...,...,...,...,...,...,...,...,...,...
10769,39,C,99,09/12/2019,895.00,False,9.644444,0.834256,7.716
10770,39,A,99,03/02/2020,350.00,False,15.938889,0.887619,7.244
10771,39,A,99,08/06/2020,450.00,False,27.288889,0.911922,6.989
10772,39,A,99,13/07/2020,0.06,False,25.644444,0.860145,6.623
10773,39,A,99,05/10/2020,915.00,False,22.250000,0.955511,6.228

In [20]:
# Crea un nuevo DataFrame que contenga las ventas de la tienda 1 y el departamento 1)
filtro= (df['store']==1) & (df['department']==1)
df_filtro=df[filtro]
display(df_filtro)

,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,1,A,1,05/02/2018,24924.50,False,5.727778,0.679451,8.106
1,1,C,1,05/03/2018,21827.90,False,8.055556,0.693452,8.106
2,1,A,1,02/04/2018,57258.43,False,16.816667,0.718284,7.808
3,1,A,1,07/05/2018,17413.94,False,22.527778,0.748928,7.808
4,1,A,1,04/06/2018,17558.09,False,27.050000,0.714586,7.808
5,1,A,1,02/07/2018,16333.14,False,27.172222,0.705076,7.787
6,1,A,1,06/08/2018,17508.41,False,30.644444,0.693980,7.787
7,1,C,1,03/09/2018,16241.78,False,27.338889,0.680772,7.787
8,1,A,1,01/10/2018,20094.19,False,22.161111,0.687640,7.838
9,1,A,1,05/11/2018,34238.88,False,14.855556,0.710359,7.838
10,1,A,1,03/12/2018,22517.56,False,9.594444,0.715378,7.838
11,1,A,1,07/01/2019,15984.24,False,9.038889,0.786176,7.742

In [21]:
# Ordena por fecha
df_filtro

# Crea un nuevo campo calculando la venta acumulada semanal
df_filtro['ventas_acumuladas'] = df_filtro['weekly_sales'].cumsum()
display(df_filtro)

# Crea un nuevo campo campo calculado con la venta acumulada máxima

df_filtro['venta_max_acumulada']= df['weekly_sales'].cummax()
# Vamos a ver los campos que acabas de crear
display(df_filtro)

,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment,ventas_acumuladas
0,1,A,1,05/02/2018,24924.50,False,5.727778,0.679451,8.106,24924.50
1,1,C,1,05/03/2018,21827.90,False,8.055556,0.693452,8.106,46752.40
2,1,A,1,02/04/2018,57258.43,False,16.816667,0.718284,7.808,104010.83
3,1,A,1,07/05/2018,17413.94,False,22.527778,0.748928,7.808,121424.77
4,1,A,1,04/06/2018,17558.09,False,27.050000,0.714586,7.808,138982.86
5,1,A,1,02/07/2018,16333.14,False,27.172222,0.705076,7.787,155316.00
6,1,A,1,06/08/2018,17508.41,False,30.644444,0.693980,7.787,172824.41
7,1,C,1,03/09/2018,16241.78,False,27.338889,0.680772,7.787,189066.19
8,1,A,1,01/10/2018,20094.19,False,22.161111,0.687640,7.838,209160.38
9,1,A,1,05/11/2018,34238.88,False,14.855556,0.710359,7.838,243399.26
10,1,A,1,03/12/2018,22517.56,False,9.594444,0.715378,7.838,265916.82
11,1,A,1,07/01/2019,15984.24,False,9.038889,0.786176,7.742,281901.06

,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment,ventas_acumuladas,venta_max_acumulada
0,1,A,1,05/02/2018,24924.50,False,5.727778,0.679451,8.106,24924.50,24924.50
1,1,C,1,05/03/2018,21827.90,False,8.055556,0.693452,8.106,46752.40,24924.50
2,1,A,1,02/04/2018,57258.43,False,16.816667,0.718284,7.808,104010.83,57258.43
3,1,A,1,07/05/2018,17413.94,False,22.527778,0.748928,7.808,121424.77,57258.43
4,1,A,1,04/06/2018,17558.09,False,27.050000,0.714586,7.808,138982.86,57258.43
5,1,A,1,02/07/2018,16333.14,False,27.172222,0.705076,7.787,155316.00,57258.43
6,1,A,1,06/08/2018,17508.41,False,30.644444,0.693980,7.787,172824.41,57258.43
7,1,C,1,03/09/2018,16241.78,False,27.338889,0.680772,7.787,189066.19,57258.43
8,1,A,1,01/10/2018,20094.19,False,22.161111,0.687640,7.838,209160.38,57258.43
9,1,A,1,05/11/2018,34238.88,False,14.855556,0.710359,7.838,243399.26,57258.43
10,1,A,1,03/12/2018,22517.56,False,9.594444,0.715378,7.838,265916.82,57258.43
11,1,A,1,07/01/2019,15984.24,False,9.038889,0.786176,7.742,281901.06,57258.43

## Eliminando duplicados de un DataFrame
<p>Eliminar duplicados es una habilidad esencial para obtener análisis precisos porque, a menudo, no deseamos tener valores repetidos dentro de nuestros cálculos.</p>

In [22]:
# Elimina los duplicados de las combinaciones store/type
df

# Resultado

,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,1,A,1,05/02/2018,24924.50,False,5.727778,0.679451,8.106
1,1,C,1,05/03/2018,21827.90,False,8.055556,0.693452,8.106
2,1,A,1,02/04/2018,57258.43,False,16.816667,0.718284,7.808
3,1,A,1,07/05/2018,17413.94,False,22.527778,0.748928,7.808
4,1,A,1,04/06/2018,17558.09,False,27.050000,0.714586,7.808
...,...,...,...,...,...,...,...,...,...
10769,39,C,99,09/12/2019,895.00,False,9.644444,0.834256,7.716
10770,39,A,99,03/02/2020,350.00,False,15.938889,0.887619,7.244
10771,39,A,99,08/06/2020,450.00,False,27.288889,0.911922,6.989
10772,39,A,99,13/07/2020,0.06,False,25.644444,0.860145,6.623
10773,39,A,99,05/10/2020,915.00,False,22.250000,0.955511,6.228

In [23]:
# Elimina los duplicados de las combinaciones store/department y ordena por venta semanal
tiendas_duplicados=df.drop_duplicates(subset=['store', 'department']).sort_values(by='weekly_sales')

# Resultado
display(tiendas_duplicados)

,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
6806,19,A,47,04/06/2018,-70.00,False,20.488889,0.794102,8.185
3215,6,A,47,05/02/2018,-59.00,False,4.683333,0.679451,7.259
7900,20,A,77,15/04/2019,-29.97,False,12.777778,1.009402,7.287
9691,31,A,78,05/02/2018,-12.00,False,3.916667,0.679451,8.324
10103,39,A,19,14/05/2018,-11.00,False,25.272222,0.753947,8.464
...,...,...,...,...,...,...,...,...,...
1703,2,A,92,05/02/2018,178982.89,False,4.550000,0.679451,8.324
8017,20,A,92,05/02/2018,195223.84,False,-3.377778,0.735455,8.187
6237,14,A,95,05/02/2018,213042.66,False,-2.605556,0.735455,8.992
4271,10,B,72,05/02/2018,232558.51,False,12.411111,0.782478,9.765
6201,14,A,92,05/02/2018,293966.05,False,-2.605556,0.735455,8.992

In [24]:
tiendas_dept =df.drop_duplicates(subset=['store','department']).sort_values(by='weekly_sales')
tiendas_dept

,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
6806,19,A,47,04/06/2018,-70.00,False,20.488889,0.794102,8.185
3215,6,A,47,05/02/2018,-59.00,False,4.683333,0.679451,7.259
7900,20,A,77,15/04/2019,-29.97,False,12.777778,1.009402,7.287
9691,31,A,78,05/02/2018,-12.00,False,3.916667,0.679451,8.324
10103,39,A,19,14/05/2018,-11.00,False,25.272222,0.753947,8.464
...,...,...,...,...,...,...,...,...,...
1703,2,A,92,05/02/2018,178982.89,False,4.550000,0.679451,8.324
8017,20,A,92,05/02/2018,195223.84,False,-3.377778,0.735455,8.187
6237,14,A,95,05/02/2018,213042.66,False,-2.605556,0.735455,8.992
4271,10,B,72,05/02/2018,232558.51,False,12.411111,0.782478,9.765
6201,14,A,92,05/02/2018,293966.05,False,-2.605556,0.735455,8.992

In [25]:
# Filtra las filas en donde las ventas hayan sido en días festivos ('is_holiday') y borra los duplicados de las fechas
filtro= df['is_holiday']==True
fechas_festivas=df[filtro]
fechas_festivas=fechas_festivas.drop_duplicates(subset=['date'])
display(fechas_festivas)

# Resultado

,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
498,1,A,45,10/09/2018,11.47,True,25.938889,0.677602,7.787
691,1,A,77,25/11/2019,1431.00,True,15.633333,0.854861,7.866
2315,4,A,47,12/02/2018,498.00,True,-1.755556,0.679715,8.623
6735,19,A,39,07/09/2020,13.41,True,22.333333,1.076766,8.193
6810,19,A,47,31/12/2018,-449.00,True,-1.861111,0.881278,8.067
6815,19,A,47,10/02/2020,15.00,True,0.338889,1.010723,7.943
6820,19,A,48,09/09/2019,197.00,True,20.155556,1.038197,7.806

## Conteo y proporción
<p>Contar es una excelente manera de obtener una descripción general de nuestro conjunto datos y poder analizar sobre todo nuestras categorías top o en su defecto las que menor proporción tienen con respecto una variable</p>

In [26]:
# Contar el número de cada tipo de tiedas
df['type'].value_counts()

type
A    9766
B     902
C     106
Name: count, dtype: int64

In [27]:
# Dar la proporcion del cálculo anterior
df['type'].value_counts(normalize=True)*100

type
A    90.644143
B     8.372007
C     0.983850
Name: proportion, dtype: float64

In [28]:
# Contar por tienda y ordenar el resultado
df['store'].value_counts(sort=True)

store
13    913
20    910
19    906
10    902
1     901
4     901
27    900
2     897
6     894
31    890
14    885
39    875
Name: count, dtype: int64

In [29]:
# Dar la proporción ordenada del cálculo anterior
df['store'].value_counts(sort=True, normalize=True)*100

store
13    8.474104
20    8.446260
19    8.409133
10    8.372007
1     8.362725
4     8.362725
27    8.353443
2     8.325599
6     8.297754
31    8.260627
14    8.214219
39    8.121403
Name: proportion, dtype: float64

## Porcentaje de ventas
<p>Walmart distingue tres tipos de tiendas: "supercenters", "discount stores" y "neighborhood markets", codificados en este conjunto de datos como tipo "A", "B" y "C". En este ejercicio, vamos a calcular las ventas totales realizadas en cada tipo de tienda, sin utilizar <code>.groupby()</code>.</p>

In [30]:
# Calcular el total de ventas semanales
ventas_totales=df['weekly_sales'].sum()

# Calcular las ventas semanales para supercenters
ventas_A=df[df['type']=='A']['weekly_sales'].sum()

# Calcular las ventas semanales para discount stores
ventas_B=df[df['type']=='B']['weekly_sales'].sum()

# Calcular las ventas semanales para neighborhood markets
ventas_C=df[df['type']=='C']['weekly_sales'].sum()

# Calcular la proporción de venta por tipo de tienda
proporción = [ventas_A, ventas_B, ventas_C]/ventas_totales*100

print('ventas_totales:',ventas_totales)

print('ventas tienda A:',ventas_A)
print('ventas tienda B:',ventas_B)
print('ventas_tienda C:',ventas_C)
print('proporción:',proporción)

ventas_totales: 256894718.89999998
ventas tienda A: 231138021.57999998
ventas tienda B: 23178403.89
ventas_tienda C: 2578293.4299999997
proporción: [89.97383153  9.02253031  1.00363816]

## Group by
<p> Podemos ahorrarnos mucho código usando el método <code>.groupby</code> como veremos a continuación</p>

In [31]:
# Calcular las ventas por tipo de tienda usando .groupby()
agrupado= df.groupby(['store','type'])['weekly_sales'].sum()
# Calcular la proporción
agrupado= df.groupby(['store','type'])['weekly_sales'].sum()/ventas_totales*100

# Resultado
display(agrupado)

store  type
1      A        7.020016
       C        0.309112
2      A        9.105702
       C        0.153398
4      A        9.153440
       C        0.010008
6      A        7.279117
       C        0.224230
10     B        9.022530
13     A        9.120681
       C        0.000319
14     A       10.411175
       C        0.056087
19     A        7.003265
       C        0.025816
20     A       10.054048
27     A        8.480800
31     A        6.271481
       C        0.026527
39     A        6.074107
       C        0.198140
Name: weekly_sales, dtype: float64

In [32]:
# Para cada tipo de tienda calcular la venta mínima, máxima, el promedio y la media (Usar las funciones NumPy)
agrupado_2=df.groupby('type')['weekly_sales'].agg([min,max,np.mean,np.median])

# Resultado
display(agrupado_2)

          min        max          mean     median
type
A    -1098.00  293966.05  23667.624573  11910.165
B     -798.00  232558.51  25696.678370  13336.080
C        0.01  104161.40  24323.522925  16643.205

In [33]:
# Para cada tipo de tienda, agrega los campos 'unemployment' y 'fuel_price_usd_per_l' y calcula el min, max, promedio y mediana
agrupado_3=df.groupby('type')[['weekly_sales','unemployment','fuel_price_usd_per_l']].agg([min,max,np.mean,np.median])

# Resultado
display(agrupado_3)

     weekly_sales                                     unemployment         \
              min        max          mean     median          min    max
type
A        -1098.00  293966.05  23667.624573  11910.165        3.879  8.992
B         -798.00  232558.51  25696.678370  13336.080        7.170  9.765
C            0.01  104161.40  24323.522925  16643.205        6.858  8.899

                      fuel_price_usd_per_l
          mean median                  min       max      mean    median
type
A     7.974131  8.067             0.670997  1.107410  0.744943  0.735455
B     9.279323  9.199             0.760023  1.107674  0.805858  0.803348
C     7.832519  7.838             0.664129  0.921433  0.714793  0.710359

## Pivot Tables
<p> Las tablas dinámicas son la forma estándar de agregar datos en hojas de cálculo. En pandas, las tablas dinámicas son esencialmente otra forma de realizar cálculos agrupados. Es decir, el método <code>.pivot_table()</code> es justamente una alternativa a <code>.groupby()</code>.</p>

In [39]:
display(sales)

NameError: name 'sales' is not defined

In [34]:
# Calcular el promedio de ventas semanales por tipo de tienda con el metodo .pivot_table() 
pivote=df.pivot_table(index = 'type', values= 'weekly_sales', aggfunc='sum')
# Resultado
display(pivote)

      weekly_sales
type
A     2.311380e+08
B     2.317840e+07
C     2.578293e+06

In [37]:
# Calcular el promedio y la mediana de ventas semanales por tipo de tienda 
pivote_2=df.pivot_table(index = 'type', values='weekly_sales', aggfunc=['mean','median'])

# Resultado
display(pivote_2)

              mean       median
      weekly_sales weekly_sales
type
A     23667.624573    11910.165
B     25696.678370    13336.080
C     24323.522925    16643.205

In [38]:
# Calcular el promedio de ventas semanales por tipo de tienda y departamento
pivote_3= df.pivot_table(index=['type','department'],values='weekly_sales',aggfunc='mean')
# Resultado
display(pivote_3)

                  weekly_sales
type department
A    1            31145.215923
     2            67736.748231
     3            17124.044538
     4            44265.151679
     5            34942.639618
...                        ...
C    95          104161.400000
     96           26941.770000
     97           27077.523333
     98           10912.088000
     99             447.505000

[215 rows x 1 columns]

In [40]:
pivote_3=df.pivot_table(index='type',columns='department',values='weekly_sales',aggfunc='mean')
display(pivote_3)

department,1,2,3,4,5,6,7,8,9,10,...,90,91,92,93,94,95,96,97,98,99
type,,,,,,,,,,,,,,,,,,,,,
A,31145.215923,67736.748231,17124.044538,44265.151679,34942.639618,7148.067923,38454.336818,48760.375923,30128.285420,30973.058308,...,86481.003594,70523.646769,139722.204773,53558.815116,60081.798203,124084.721374,21184.264918,28503.679612,12952.719843,377.993388
B,44050.626667,112958.526667,30580.655000,51219.654167,63236.875000,10717.297500,52909.653333,90733.753333,66679.301667,48595.126667,...,14780.210000,13199.602500,50859.278333,1466.274167,161.445833,77082.102500,9528.538333,5828.873333,217.428333,NaN
C,19034.840000,58721.845000,19497.300000,46937.810000,18887.710000,6370.900000,NaN,37084.935000,29094.000000,28161.330000,...,63245.780000,63891.865000,NaN,47170.843333,60060.582500,104161.400000,26941.770000,27077.523333,10912.088000,447.505000

In [41]:
# Calcular el promedio de ventas semanales por tipo de tienda y departamento, reemplazando los valores nulos con 0
pivote_4=df.pivot_table(index='type',columns='department',values='weekly_sales',aggfunc='mean',fill_value=0)

# Resultado
display(pivote_4)

department,1,2,3,4,5,6,7,8,9,10,...,90,91,92,93,94,95,96,97,98,99
type,,,,,,,,,,,,,,,,,,,,,
A,31145.215923,67736.748231,17124.044538,44265.151679,34942.639618,7148.067923,38454.336818,48760.375923,30128.285420,30973.058308,...,86481.003594,70523.646769,139722.204773,53558.815116,60081.798203,124084.721374,21184.264918,28503.679612,12952.719843,377.993388
B,44050.626667,112958.526667,30580.655000,51219.654167,63236.875000,10717.297500,52909.653333,90733.753333,66679.301667,48595.126667,...,14780.210000,13199.602500,50859.278333,1466.274167,161.445833,77082.102500,9528.538333,5828.873333,217.428333,0.000000
C,19034.840000,58721.845000,19497.300000,46937.810000,18887.710000,6370.900000,0.000000,37084.935000,29094.000000,28161.330000,...,63245.780000,63891.865000,0.000000,47170.843333,60060.582500,104161.400000,26941.770000,27077.523333,10912.088000,447.505000

In [45]:
# Calcular el promedio de ventas semanales por tipo de tienda y departamento, reemplazando los valores nulos con 0 y sumando las filas y columnas
pivote_5=df.pivot_table(index='type',
                        columns='department',
                        values='weekly_sales',
                        aggfunc='mean',
                        fill_value=0,
                        margins=True)
# Resultado
display(pivote_5)

department,1,2,3,4,5,6,7,8,9,10,...,91,92,93,94,95,96,97,98,99,All
type,,,,,,,,,,,,,,,,,,,,,
A,31145.215923,67736.748231,17124.044538,44265.151679,34942.639618,7148.067923,38454.336818,48760.375923,30128.285420,30973.058308,...,70523.646769,139722.204773,53558.815116,60081.798203,124084.721374,21184.264918,28503.679612,12952.719843,377.993388,23667.624573
B,44050.626667,112958.526667,30580.655000,51219.654167,63236.875000,10717.297500,52909.653333,90733.753333,66679.301667,48595.126667,...,13199.602500,50859.278333,1466.274167,161.445833,77082.102500,9528.538333,5828.873333,217.428333,0.000000,25696.678370
C,19034.840000,58721.845000,19497.300000,46937.810000,18887.710000,6370.900000,0.000000,37084.935000,29094.000000,28161.330000,...,63891.865000,0.000000,47170.843333,60060.582500,104161.400000,26941.770000,27077.523333,10912.088000,447.505000,24323.522925
All,32052.467153,71380.022778,18278.390625,44863.253681,37189.000000,7434.709722,39658.946528,52095.998472,33167.020903,32402.512222,...,65654.535000,132316.960903,49084.687292,55087.846181,120029.480069,20337.607681,26584.400833,11820.590278,379.123659,23843.950149

In [46]:
pivote_5.to_csv('datos.csv')