# <span style='color:black'> <center>Unión de datos con Pandas</center> </span>
## 1. Data mergin
<p><img src="https://cdn.prgloo.com/media/13f61baf042143dca612098e751cfa07.png?width=1024&height=960" width="750"</p>

## Joins
<p>Chicago proporciona una lista de propietarios de taxis y vehículos con licencia para operar dentro de la ciudad, esto por por seguridad pública. Tu objetivo es unir dos tablas. Una tabla se llama <code>taxi_owners.p</code>, con información sobre los propietarios de la empresa de taxis, y otra se llama <code>taxi_vehicle.p</code>, con información sobre cada vehículo de taxi. No olvides cargar las tablas antes de comenzar

Elija la columna que usaría para fusionar las dos tablas sobre el uso del método <code>.merge()</code> y complete los ejercicios </p>

In [5]:
# Importa pandas
import os

import pandas as pd

# Importa datasets
import pandas as pd

taxi_owners = pd.read_pickle(
    r"C:\Users\usuario\OneDrive\Escritorio\Python repositorios\python-basics\Data excel para manejo de librería Pandas\Data\taxi_owners.p"
)

display(taxi_owners)
taxi_vehicle = pd.read_pickle(
    r"C:\Users\usuario\OneDrive\Escritorio\Python repositorios\python-basics\Data excel para manejo de librería Pandas\Data\taxi_vehicles.p"
)
display(taxi_vehicle)

        rid   vid             owner                 address    zip
0     T6285  6285    AGEAN TAXI LLC     4536 N. ELSTON AVE.  60630
1     T4862  4862      MANGIB CORP.  5717 N. WASHTENAW AVE.  60659
2     T1495  1495     FUNRIDE, INC.     3351 W. ADDISON ST.  60618
3     T4231  4231      ALQUSH CORP.   6611 N. CAMPBELL AVE.  60645
4     T5971  5971    EUNIFFORD INC.     3351 W. ADDISON ST.  60618
...     ...   ...               ...                     ...    ...
3514  T4453  4453   IMAGIN CAB CORP     3351 W. ADDISON ST.  60618
3515   T121   121  TRIBECA CAB CORP     4536 N. ELSTON AVE.  60630
3516  T3465  3465  AMIR EXPRESS INC     3351 W. ADDISON ST.  60618
3517  T1962  1962  KARY CAB COMPANY     4707 N. KENTON AVE.  60630
3518  T1031  1031       NECT 42 LLC    6500 N. WESTERN AVE.  60645

[3519 rows x 5 columns]

       vid     make    model  year  fuel_type                owner
0     2767   TOYOTA    CAMRY  2013     HYBRID       SEYED M. BADRI
1     1411   TOYOTA     RAV4  2017     HYBRID          DESZY CORP.
2     6500   NISSAN   SENTRA  2019   GASOLINE       AGAPH CAB CORP
3     2746   TOYOTA    CAMRY  2013     HYBRID  MIDWEST CAB CO, INC
4     5922   TOYOTA    CAMRY  2013     HYBRID       SUMETTI CAB CO
...    ...      ...      ...   ...        ...                  ...
3514  5902   TOYOTA    CAMRY  2013     HYBRID            SAFAR INC
3515  1407  HYUNDAI  ELANTRA  2018   GASOLINE    MYKONOS CAB CORP.
3516   854   TOYOTA    CAMRY  2012     HYBRID      JOELIZ CORP INC
3517  6274   TOYOTA    CAMRY  2012     HYBRID          A K O S INC
3518  4675     FORD   ESCAPE  2011  FLEX FUEL           MAJAZ CORP

[3519 rows x 6 columns]

In [6]:
# Visualiza las primeras 5 entradas de cada dataset
display(taxi_owners)
display(taxi_vehicle)

        rid   vid             owner                 address    zip
0     T6285  6285    AGEAN TAXI LLC     4536 N. ELSTON AVE.  60630
1     T4862  4862      MANGIB CORP.  5717 N. WASHTENAW AVE.  60659
2     T1495  1495     FUNRIDE, INC.     3351 W. ADDISON ST.  60618
3     T4231  4231      ALQUSH CORP.   6611 N. CAMPBELL AVE.  60645
4     T5971  5971    EUNIFFORD INC.     3351 W. ADDISON ST.  60618
...     ...   ...               ...                     ...    ...
3514  T4453  4453   IMAGIN CAB CORP     3351 W. ADDISON ST.  60618
3515   T121   121  TRIBECA CAB CORP     4536 N. ELSTON AVE.  60630
3516  T3465  3465  AMIR EXPRESS INC     3351 W. ADDISON ST.  60618
3517  T1962  1962  KARY CAB COMPANY     4707 N. KENTON AVE.  60630
3518  T1031  1031       NECT 42 LLC    6500 N. WESTERN AVE.  60645

[3519 rows x 5 columns]

       vid     make    model  year  fuel_type                owner
0     2767   TOYOTA    CAMRY  2013     HYBRID       SEYED M. BADRI
1     1411   TOYOTA     RAV4  2017     HYBRID          DESZY CORP.
2     6500   NISSAN   SENTRA  2019   GASOLINE       AGAPH CAB CORP
3     2746   TOYOTA    CAMRY  2013     HYBRID  MIDWEST CAB CO, INC
4     5922   TOYOTA    CAMRY  2013     HYBRID       SUMETTI CAB CO
...    ...      ...      ...   ...        ...                  ...
3514  5902   TOYOTA    CAMRY  2013     HYBRID            SAFAR INC
3515  1407  HYUNDAI  ELANTRA  2018   GASOLINE    MYKONOS CAB CORP.
3516   854   TOYOTA    CAMRY  2012     HYBRID      JOELIZ CORP INC
3517  6274   TOYOTA    CAMRY  2012     HYBRID          A K O S INC
3518  4675     FORD   ESCAPE  2011  FLEX FUEL           MAJAZ CORP

[3519 rows x 6 columns]

In [7]:
# Une las dos tablas
taxi_own_veh= taxi_owners.merge(taxi_vehicle, on= 'vid', how='inner')
display(taxi_own_veh)

,rid,vid,owner_x,address,zip,make,model,year,fuel_type,owner_y
0,T6285,6285,AGEAN TAXI LLC,4536 N. ELSTON AVE.,60630,NISSAN,ALTIMA,2011,HYBRID,AGEAN TAXI LLC
1,T4862,4862,MANGIB CORP.,5717 N. WASHTENAW AVE.,60659,HONDA,CRV,2014,GASOLINE,MANGIB CORP.
2,T1495,1495,"FUNRIDE, INC.",3351 W. ADDISON ST.,60618,TOYOTA,SIENNA,2015,GASOLINE,"FUNRIDE, INC."
3,T4231,4231,ALQUSH CORP.,6611 N. CAMPBELL AVE.,60645,TOYOTA,CAMRY,2014,HYBRID,ALQUSH CORP.
4,T5971,5971,EUNIFFORD INC.,3351 W. ADDISON ST.,60618,TOYOTA,SIENNA,2015,GASOLINE,EUNIFFORD INC.
...,...,...,...,...,...,...,...,...,...,...
3514,T4453,4453,IMAGIN CAB CORP,3351 W. ADDISON ST.,60618,FORD,ESCAPE,2010,HYBRID,IMAGIN CAB CORP
3515,T121,121,TRIBECA CAB CORP,4536 N. ELSTON AVE.,60630,FORD,C-MAX,2014,HYBRID,TRIBECA CAB CORP
3516,T3465,3465,AMIR EXPRESS INC,3351 W. ADDISON ST.,60618,TOYOTA,CAMRY,2014,HYBRID,AMIR EXPRESS INC
3517,T1962,1962,KARY CAB COMPANY,4707 N. KENTON AVE.,60630,TOYOTA,CAMRY,2014,HYBRID,KARY CAB COMPANY
3518,T1031,1031,NECT 42 LLC,6500 N. WESTERN AVE.,60645,FORD,FUSION,2014,HYBRID,NECT 42 LLC

In [8]:
# Imprime el tamaño de cada una de las tablas
print(taxi_owners.shape)
print(taxi_vehicle.shape)
print(taxi_own_veh.shape)

(3519, 5)
(3519, 6)
(3519, 10)

In [9]:
# Une las dos tablas usando los sufijos '_own', '_veh'
taxi_own_veh= taxi_owners.merge(taxi_vehicle, on= 'vid', how='inner', suffixes= ('_tabla1','_tabla2'))
display(taxi_own_veh)

,rid,vid,owner_tabla1,address,zip,make,model,year,fuel_type,owner_tabla2
0,T6285,6285,AGEAN TAXI LLC,4536 N. ELSTON AVE.,60630,NISSAN,ALTIMA,2011,HYBRID,AGEAN TAXI LLC
1,T4862,4862,MANGIB CORP.,5717 N. WASHTENAW AVE.,60659,HONDA,CRV,2014,GASOLINE,MANGIB CORP.
2,T1495,1495,"FUNRIDE, INC.",3351 W. ADDISON ST.,60618,TOYOTA,SIENNA,2015,GASOLINE,"FUNRIDE, INC."
3,T4231,4231,ALQUSH CORP.,6611 N. CAMPBELL AVE.,60645,TOYOTA,CAMRY,2014,HYBRID,ALQUSH CORP.
4,T5971,5971,EUNIFFORD INC.,3351 W. ADDISON ST.,60618,TOYOTA,SIENNA,2015,GASOLINE,EUNIFFORD INC.
...,...,...,...,...,...,...,...,...,...,...
3514,T4453,4453,IMAGIN CAB CORP,3351 W. ADDISON ST.,60618,FORD,ESCAPE,2010,HYBRID,IMAGIN CAB CORP
3515,T121,121,TRIBECA CAB CORP,4536 N. ELSTON AVE.,60630,FORD,C-MAX,2014,HYBRID,TRIBECA CAB CORP
3516,T3465,3465,AMIR EXPRESS INC,3351 W. ADDISON ST.,60618,TOYOTA,CAMRY,2014,HYBRID,AMIR EXPRESS INC
3517,T1962,1962,KARY CAB COMPANY,4707 N. KENTON AVE.,60630,TOYOTA,CAMRY,2014,HYBRID,KARY CAB COMPANY
3518,T1031,1031,NECT 42 LLC,6500 N. WESTERN AVE.,60645,FORD,FUSION,2014,HYBRID,NECT 42 LLC

In [12]:
# Encuentra el tipo de combustible más popular que usa cada taxi 
#(Hint: Puedes usar la propiedad .value_counts())
taxi_own_veh['fuel_type'].value_counts()

fuel_type
HYBRID                    2792
GASOLINE                   611
FLEX FUEL                   89
COMPRESSED NATURAL GAS      27
Name: count, dtype: int64

Esto me lo da en % para saber el tamaño de la proporción

In [11]:
taxi_own_veh['fuel_type'].value_counts(normalize=True)*100

fuel_type
HYBRID                    79.340722
GASOLINE                  17.362887
FLEX FUEL                  2.529128
COMPRESSED NATURAL GAS     0.767263
Name: proportion, dtype: float64

In [13]:
# Encuentra la empresa con más autos disponibles con conductor registrado
taxi_own_veh['owner_tabla1'].value_counts().sort_values(ascending=False)

owner_tabla1
CHICAGO SEVEN INC               21
AQUARIUS CAB INC.               12
CHICAGO MEDALLION ONE LLC.      10
CHICAGO MEDALLION THREE LLC.    10
CAPRICORN CAB INC                9
                                ..
FELIX MANZANAREZ                 1
KAUSAR, INC.                     1
SALSABIL INC.                    1
AMIR EXPRESS INC                 1
KARY CAB COMPANY                 1
Name: count, Length: 2375, dtype: int64

## ¿Que es un inner join?
<p>Un <b>inner join</b> devuelve todas las filas cuando hay valores que coinciden en ambas tablas. Explorarás esto más a fondo al revisar la union entre la tabla de <code>ward</code> y la tabla de <code>census</code>. </p> 

El dataset <code>ward</code> contiene información sobre ciertas divisiones administrativas dentro de una ciudad junto con sus concejales, por otra parte el dataset <code>census</code> contiene información sobre el censo de dichas divisiones.

In [15]:
# Importa datasets
ward = pd.read_pickle(
    r"C:\Users\usuario\OneDrive\Escritorio\Python repositorios\python-basics\Data excel para manejo de librería Pandas\Data\ward.p"
)

In [18]:
census = pd.read_pickle(
    r"C:\Users\usuario\OneDrive\Escritorio\Python repositorios\python-basics\Data excel para manejo de librería Pandas\Data\census.p"
    )

In [19]:
# imprime los primeros 5 registros
display(ward)
display(census)

   ward                   alderman                            address    zip
0     1         Proco "Joe" Moreno          2058 NORTH WESTERN AVENUE  60647
1     2              Brian Hopkins         1400 NORTH  ASHLAND AVENUE  60622
2     3                 Pat Dowell            5046 SOUTH STATE STREET  60609
3     4           William D. Burns    435 EAST 35TH STREET, 1ST FLOOR  60616
4     5         Leslie A. Hairston              2325 EAST 71ST STREET  60649
5     6         Roderick T. Sawyer   8001 S. MARTIN LUTHER KING DRIVE  60619
6     7        Gregory I. Mitchell              2249 EAST 95TH STREET  60617
7     8         Michelle A. Harris    8539 SOUTH COTTAGE GROVE AVENUE  60619
8     9           Anthony A. Beale                34 EAST 112TH PLACE  60628
9    10      Susan Sadlowski Garza           10500 SOUTH EWING AVENUE  60617
10   11     Patrick Daley Thompson          3659 SOUTH HALSTED STREET  60609
11   12            George Cardenas           3476 SOUTH ARCHER AVENUE  60608
12   13                Marty Quinn            6500 SOUTH PULASKI ROAD  60629
13   14            Edward M. Burke              2650 WEST 51ST STREET  60632
14   15           Raymond A. Lopez              1650 WEST 63RD STREET  60636
15   16            Toni L. Foulkes              3045 WEST 63RD STREET  60629
16   17             David H. Moore          7313 SOUTH ASHLAND AVENUE  60636
17   18          Derrick G. Curtis            8359 SOUTH PULASKI ROAD  60652
18   19          Matthew J. O'Shea         10400 SOUTH WESTERN AVENUE  60643
19   20          Willie B. Cochran    6357 SOUTH COTTAGE GROVE AVENUE  60637
20   21    Howard B. Brookins, Jr.  9011 SOUTH ASHLAND AVENUE, UNIT B  60620
21   22              Ricardo Munoz        2500 SOUTH ST. LOUIS AVENUE  60623
22   23        Michael R. Zalewski           6247 SOUTH ARCHER AVENUE  60638
23   24         Michael Scott, Jr.           1158 SOUTH KEELER AVENUE  60624
24   25       Daniel "Danny" Solis      1800 SOUTH BLUE ISLAND AVENUE  60608
25   26          Roberto Maldonado          2511 WEST DIVISION STREET  60622
26   27        Walter Burnett, Jr.             4 NORTH WESTERN AVENUE  60612
27   28             Jason C. Ervin              2602 WEST 16TH STREET  60612
28   29           Chris Taliaferro             6272 WEST NORTH AVENUE  60639
29   30          Ariel E. Reyboras        3559 NORTH MILWAUKEE AVENUE  60641
30   31  Milagros "Milly" Santiago            2521 NORTH PULASKI ROAD  60639
31   32           Scott Waguespack         2657 NORTH CLYBOURN AVENUE  60614
32   33               Deborah Mell         3001 WEST IRVING PARK ROAD  60618
33   34           Carrie M. Austin              507 WEST 111TH STREET  60628
34   35        Carlos Ramirez-Rosa           2710 NORTH SAWYER AVENUE  60647
35   36           Gilbert Villegas                 6934 WEST DIVERSEY  60607
36   37              Emma M. Mitts           4924 WEST CHICAGO AVENUE  60651
37   38           Nicholas Sposato          3821  NORTH HARLEM AVENUE  60634
38   39           Margaret Laurino          4404 WEST LAWRENCE AVENUE  60630
39   40        Patrick J. O'Connor          5850 NORTH LINCOLN AVENUE  60659
40   41      Anthony V. Napolitano           7442 NORTH HARLEM AVENUE  60631
41   42             Brendan Reilly   325 WEST HURON STREET, SUITE 510  60654
42   43             Michelle Smith          2523 NORTH HALSTED STREET  60614
43   44                 Tom Tunney        3223 NORTH SHEFFIELD AVENUE  60657
44   45              John S. Arena        4754 NORTH MILWAUKEE AVENUE  60630
45   46            James Cappleman         4544 NORTH BROADWAY AVENUE  60640
46   47                Ameya Pawar          4243 NORTH LINCOLN AVENUE  60618
47   48             Harry Osterman         5533 NORTH BROADWAY AVENUE  60640
48   49                  Joe Moore        7356 NORTH GREENVIEW AVENUE  60626
49   50       Debra L. Silverstein    2949 WEST DEVON AVENUE, SUITE A  60659

,ward,pop_2000,pop_2010,change,address,zip
0,1,52951,56149,6%,2765 WEST SAINT MARY STREET,60647
1,2,54361,55805,3%,WM WASTE MANAGEMENT 1500,60622
2,3,40385,53039,31%,17 EAST 38TH STREET,60653
3,4,51953,54589,5%,31ST ST HARBOR BUILDING LAKEFRONT TRAIL,60653
4,5,55302,51455,-7%,JACKSON PARK LAGOON SOUTH CORNELL DRIVE,60637
5,6,54989,52341,-5%,150 WEST 74TH STREET,60636
6,7,54593,51581,-6%,8549 SOUTH OGLESBY AVENUE,60617
7,8,54039,51687,-4%,1346-1352 EAST 75TH STREET,60649
8,9,52008,51519,-1%,11039-11059 SOUTH WENTWORTH AVENUE,60628
9,10,56613,51535,-9%,10534 SOUTH AVENUE F,46394
10,11,64228,51497,-20%,943-947 WEST 14TH PLACE,60607
11,12,68922,52235,-24%,CP 46 STEVENSON EXPRESSWAY,60632
12,13,64382,53722,-17%,SOUTH RAMP SOUTH LARAMIE AVENUE,60638
13,14,80143,54031,-33%,4540 WEST 51ST STREET,60632
14,15,56057,51501,-8%,CHICAGO FIRE DEPARTMENT ENGINE COMPANY 123 2215,60632
15,16,50205,51954,3%,6036 SOUTH WOOD STREET,60636
16,17,49264,51846,5%,7216 SOUTH WINCHESTER AVENUE,60636
17,18,55043,52992,-4%,3286 WEST COLUMBUS AVENUE,60652
18,19,54546,51525,-6%,9999 SOUTH FRANCISCO AVENUE,60805
19,20,51854,52372,1%,DAN RYAN EXPRESSWAY PARK MANOR,60621
20,21,51751,51632,0%,8852-8854 SOUTH EMERALD AVENUE,60620
21,22,59734,53515,-10%,4233 WEST 36TH STREET,60632
22,23,63691,53728,-16%,CHICAGO MIDWAY INTERNATIONAL AIRPORT WEST 62ND...,60629
23,24,50879,54909,8%,1635 SOUTH CHRISTIANA AVENUE,60623
24,25,55954,54539,-3%,1632-1746 SOUTH MILLER STREET,60608
25,26,56841,53516,-6%,LITTLE CUBS FIELD COMFORT STATION 1400,60622
26,27,61287,52939,-14%,2151-2153 WEST CHICAGO AVENUE,60651
27,28,49423,55199,12%,RML SPECIALTY HOSPITAL 3435,60624
28,29,61949,55267,-11%,1241 NORTH RIDGELAND AVENUE,60302
29,30,72698,55560,-24%,5118 WEST FLETCHER STREET,60641
30,31,65045,53724,-17%,2854 NORTH KEATING AVENUE,60641
31,32,57204,55184,-4%,2901 NORTH WASHTENAW AVENUE,60618
32,33,63695,55598,-13%,4041-4043 NORTH RICHMOND STREET,60625
33,34,49922,51599,3%,11544-11546 SOUTH PEORIA STREET,60827
34,35,57588,55281,-4%,3634 WEST BELMONT AVENUE,60618
35,36,63376,54766,-14%,2918 NORTH RUTHERFORD AVENUE,60634
36,37,56120,51538,-8%,4738-4748 WEST RICE STREET,60651
37,38,66011,56001,-15%,7307-7331 WEST IRVING PARK ROAD,60706
38,39,64291,55882,-13%,QUEEN OF ALL SAINTS BASILICA 6280,60646
39,40,58652,55319,-6%,5536 NORTH ARTESIAN AVENUE,60645
40,41,56127,55991,0%,1652 SOUTH CLIFTON AVENUE,60068
41,42,68102,55870,-18%,410-420 WEST GRAND AVENUE,60654
42,43,57668,56170,-3%,LINCOLN PARK ZOO 2001,60614
43,44,58758,56058,-5%,507-513 WEST ALDINE AVENUE,60657
44,45,60653,55967,-8%,CONGREGATIONAL CHURCH OF JEFFERSON PARK 5320,60630
45,46,56587,53784,-5%,UPTOWN BROADWAY BUILDING 4743-4763,60640
46,47,52108,55074,6%,2153 WEST BERTEAU AVENUE,60618
47,48,56246,55014,-2%,1025 WEST HOLLYWOOD AVENUE,60660
48,49,59435,54633,-8%,1426 WEST ESTES AVENUE,60645
49,50,62383,55809,-11%,2638 WEST NORTH SHORE AVENUE,60645

In [20]:
# Une las dos tablas
ward_census = ward.merge(census, on='ward', how = 'inner')
display(ward_census)

,ward,alderman,address_x,zip_x,pop_2000,pop_2010,change,address_y,zip_y
0,1,"Proco ""Joe"" Moreno",2058 NORTH WESTERN AVENUE,60647,52951,56149,6%,2765 WEST SAINT MARY STREET,60647
1,2,Brian Hopkins,1400 NORTH ASHLAND AVENUE,60622,54361,55805,3%,WM WASTE MANAGEMENT 1500,60622
2,3,Pat Dowell,5046 SOUTH STATE STREET,60609,40385,53039,31%,17 EAST 38TH STREET,60653
3,4,William D. Burns,"435 EAST 35TH STREET, 1ST FLOOR",60616,51953,54589,5%,31ST ST HARBOR BUILDING LAKEFRONT TRAIL,60653
4,5,Leslie A. Hairston,2325 EAST 71ST STREET,60649,55302,51455,-7%,JACKSON PARK LAGOON SOUTH CORNELL DRIVE,60637
5,6,Roderick T. Sawyer,8001 S. MARTIN LUTHER KING DRIVE,60619,54989,52341,-5%,150 WEST 74TH STREET,60636
6,7,Gregory I. Mitchell,2249 EAST 95TH STREET,60617,54593,51581,-6%,8549 SOUTH OGLESBY AVENUE,60617
7,8,Michelle A. Harris,8539 SOUTH COTTAGE GROVE AVENUE,60619,54039,51687,-4%,1346-1352 EAST 75TH STREET,60649
8,9,Anthony A. Beale,34 EAST 112TH PLACE,60628,52008,51519,-1%,11039-11059 SOUTH WENTWORTH AVENUE,60628
9,10,Susan Sadlowski Garza,10500 SOUTH EWING AVENUE,60617,56613,51535,-9%,10534 SOUTH AVENUE F,46394
10,11,Patrick Daley Thompson,3659 SOUTH HALSTED STREET,60609,64228,51497,-20%,943-947 WEST 14TH PLACE,60607
11,12,George Cardenas,3476 SOUTH ARCHER AVENUE,60608,68922,52235,-24%,CP 46 STEVENSON EXPRESSWAY,60632
12,13,Marty Quinn,6500 SOUTH PULASKI ROAD,60629,64382,53722,-17%,SOUTH RAMP SOUTH LARAMIE AVENUE,60638
13,14,Edward M. Burke,2650 WEST 51ST STREET,60632,80143,54031,-33%,4540 WEST 51ST STREET,60632
14,15,Raymond A. Lopez,1650 WEST 63RD STREET,60636,56057,51501,-8%,CHICAGO FIRE DEPARTMENT ENGINE COMPANY 123 2215,60632
15,16,Toni L. Foulkes,3045 WEST 63RD STREET,60629,50205,51954,3%,6036 SOUTH WOOD STREET,60636
16,17,David H. Moore,7313 SOUTH ASHLAND AVENUE,60636,49264,51846,5%,7216 SOUTH WINCHESTER AVENUE,60636
17,18,Derrick G. Curtis,8359 SOUTH PULASKI ROAD,60652,55043,52992,-4%,3286 WEST COLUMBUS AVENUE,60652
18,19,Matthew J. O'Shea,10400 SOUTH WESTERN AVENUE,60643,54546,51525,-6%,9999 SOUTH FRANCISCO AVENUE,60805
19,20,Willie B. Cochran,6357 SOUTH COTTAGE GROVE AVENUE,60637,51854,52372,1%,DAN RYAN EXPRESSWAY PARK MANOR,60621
20,21,"Howard B. Brookins, Jr.","9011 SOUTH ASHLAND AVENUE, UNIT B",60620,51751,51632,0%,8852-8854 SOUTH EMERALD AVENUE,60620
21,22,Ricardo Munoz,2500 SOUTH ST. LOUIS AVENUE,60623,59734,53515,-10%,4233 WEST 36TH STREET,60632
22,23,Michael R. Zalewski,6247 SOUTH ARCHER AVENUE,60638,63691,53728,-16%,CHICAGO MIDWAY INTERNATIONAL AIRPORT WEST 62ND...,60629
23,24,"Michael Scott, Jr.",1158 SOUTH KEELER AVENUE,60624,50879,54909,8%,1635 SOUTH CHRISTIANA AVENUE,60623
24,25,"Daniel ""Danny"" Solis",1800 SOUTH BLUE ISLAND AVENUE,60608,55954,54539,-3%,1632-1746 SOUTH MILLER STREET,60608
25,26,Roberto Maldonado,2511 WEST DIVISION STREET,60622,56841,53516,-6%,LITTLE CUBS FIELD COMFORT STATION 1400,60622
26,27,"Walter Burnett, Jr.",4 NORTH WESTERN AVENUE,60612,61287,52939,-14%,2151-2153 WEST CHICAGO AVENUE,60651
27,28,Jason C. Ervin,2602 WEST 16TH STREET,60612,49423,55199,12%,RML SPECIALTY HOSPITAL 3435,60624
28,29,Chris Taliaferro,6272 WEST NORTH AVENUE,60639,61949,55267,-11%,1241 NORTH RIDGELAND AVENUE,60302
29,30,Ariel E. Reyboras,3559 NORTH MILWAUKEE AVENUE,60641,72698,55560,-24%,5118 WEST FLETCHER STREET,60641
30,31,"Milagros ""Milly"" Santiago",2521 NORTH PULASKI ROAD,60639,65045,53724,-17%,2854 NORTH KEATING AVENUE,60641
31,32,Scott Waguespack,2657 NORTH CLYBOURN AVENUE,60614,57204,55184,-4%,2901 NORTH WASHTENAW AVENUE,60618
32,33,Deborah Mell,3001 WEST IRVING PARK ROAD,60618,63695,55598,-13%,4041-4043 NORTH RICHMOND STREET,60625
33,34,Carrie M. Austin,507 WEST 111TH STREET,60628,49922,51599,3%,11544-11546 SOUTH PEORIA STREET,60827
34,35,Carlos Ramirez-Rosa,2710 NORTH SAWYER AVENUE,60647,57588,55281,-4%,3634 WEST BELMONT AVENUE,60618
35,36,Gilbert Villegas,6934 WEST DIVERSEY,60607,63376,54766,-14%,2918 NORTH RUTHERFORD AVENUE,60634
36,37,Emma M. Mitts,4924 WEST CHICAGO AVENUE,60651,56120,51538,-8%,4738-4748 WEST RICE STREET,60651
37,38,Nicholas Sposato,3821 NORTH HARLEM AVENUE,60634,66011,56001,-15%,7307-7331 WEST IRVING PARK ROAD,60706
38,39,Margaret Laurino,4404 WEST LAWRENCE AVENUE,60630,64291,55882,-13%,QUEEN OF ALL SAINTS BASILICA 6280,60646
39,40,Patrick J. O'Connor,5850 NORTH LINCOLN AVENUE,60659,58652,55319,-6%,5536 NORTH ARTESIAN AVENUE,60645
40,41,Anthony V. Napolitano,7442 NORTH HARLEM AVENUE,60631,56127,55991,0%,1652 SOUTH CLIFTON AVENUE,60068
41,42,Brendan Reilly,"325 WEST HURON STREET, SUITE 510",60654,68102,55870,-18%,410-420 WEST GRAND AVENUE,60654
42,43,Michelle Smith,2523 NORTH HALSTED STREET,60614,57668,56170,-3%,LINCOLN PARK ZOO 2001,60614
43,44,Tom Tunney,3223 NORTH SHEFFIELD AVENUE,60657,58758,56058,-5%,507-513 WEST ALDINE AVENUE,60657
44,45,John S. Arena,4754 NORTH MILWAUKEE AVENUE,60630,60653,55967,-8%,CONGREGATIONAL CHURCH OF JEFFERSON PARK 5320,60630
45,46,James Cappleman,4544 NORTH BROADWAY AVENUE,60640,56587,53784,-5%,UPTOWN BROADWAY BUILDING 4743-4763,60640
46,47,Ameya Pawar,4243 NORTH LINCOLN AVENUE,60618,52108,55074,6%,2153 WEST BERTEAU AVENUE,60618
47,48,Harry Osterman,5533 NORTH BROADWAY AVENUE,60640,56246,55014,-2%,1025 WEST HOLLYWOOD AVENUE,60660
48,49,Joe Moore,7356 NORTH GREENVIEW AVENUE,60626,59435,54633,-8%,1426 WEST ESTES AVENUE,60645
49,50,Debra L. Silverstein,"2949 WEST DEVON AVENUE, SUITE A",60659,62383,55809,-11%,2638 WEST NORTH SHORE AVENUE,60645

In [21]:
# Imprime el tamaño de cada una de las tablas
print(ward.shape)
print(census.shape)
print(ward_census.shape)

(50, 4)
(50, 6)
(50, 9)

## Union uno a varios (One-to-many)
<p>Una empresa tiene multiples titulos o cargos. En este ejercicio podrás apreciar una union <b>One-to-many</b>. Para ello tendrás que unir la tabla de propietarios de empresas, llamada <code>business_owners</code>, con la tabla de <code>licenses</code>. En una relación de uno a varios, una fila en la tabla de la izquierda puede repetirse si está relacionada con varias filas en la tabla de la derecha. En el ejercicio vas a descubrir cuál es el título de propietario de negocio más común. (es decir, secretario, director ejecutivo o vicepresidente)</p>

In [26]:
# Importar datasets
business_owners = pd.read_pickle(
    r"C:\Users\usuario\OneDrive\Escritorio\Python repositorios\python-basics\Data excel para manejo de librería Pandas\Data\business_owners.p"
)
licenses = pd.read_pickle(
    r"C:\Users\usuario\OneDrive\Escritorio\Python repositorios\python-basics\Data excel para manejo de librería Pandas\Data\licenses.p"
)

In [27]:
# imprime los primeros 5 registros
display(business_owners)
display(licenses)

      account first_name  last_name           title
0          10      PEARL    SHERMAN       PRESIDENT
1          10      PEARL    SHERMAN       SECRETARY
2       10002     WALTER     MROZEK         PARTNER
3       10002     CELINA     BYRDAK         PARTNER
4       10005      IRENE  ROSENFELD       PRESIDENT
...       ...        ...        ...             ...
21347    9513     THOMAS     MAHLUM       SECRETARY
21348    9563  GUADALUPE      PEREZ       PRESIDENT
21349    9638     STEVEN     JENSEN  VICE PRESIDENT
21350    9922     MANUEL    SALAZAR       SECRETARY
21351    9933    MICHAEL       KNAB       PRESIDENT

[21352 rows x 4 columns]

,account,ward,aid,business,address,zip
0,307071,3,743,REGGIE'S BAR & GRILL,2105 S STATE ST,60616
1,10,10,829,HONEYBEERS,13200 S HOUSTON AVE,60633
2,10002,14,775,CELINA DELI,5089 S ARCHER AVE,60632
3,10005,12,NaN,KRAFT FOODS NORTH AMERICA,2005 W 43RD ST,60609
4,10044,44,638,NEYBOUR'S TAVERN & GRILLE,3651 N SOUTHPORT AVE,60613
...,...,...,...,...,...,...
9995,8634,10,NaN,J M V CORP,2717 E 95TH ST,60617
9996,86350,42,708,AMERICASH LOANS LLC,103 N WELLS ST 1ST,60606
9997,86352,23,775,MC DONALD'S,6720 W ARCHER AVE 1,60638
9998,86355,43,638,VOSGES HAUT-CHOCOLAT,951 W ARMITAGE AVE 1,60614
9999,86373,20,775,ALMUFLIHI FOOD & LIQUOR,5400-5404 S HALSTED ST 1ST,60609

In [28]:
# Unir los dos datasets por el campo 'account'
licenses_owners = licenses.merge (business_owners, on= 'account', how= 'inner')

In [29]:
# Imprime el tamaño de cada una de las tablas
display(licenses.shape)
display(business_owners.shape)
display(licenses_owners.shape)

(10000, 6)

(21352, 4)

(19497, 9)

In [31]:
#¿Cuáles son las posiciones laborales más demandadas?
licenses_owners['title'].value_counts()

title
PRESIDENT             6259
SECRETARY             5205
SOLE PROPRIETOR       1658
OTHER                 1200
VICE PRESIDENT         970
MEMBER                 884
MANAGING MEMBER        878
SHAREHOLDER            590
PARTNER                451
TREASURER              447
INDIVIDUAL             268
DIRECTOR               146
MANAGER                134
ASST. SECRETARY        111
CEO                    110
PRINCIPAL OFFICER       63
SPOUSE                  34
LIMITED PARTNER         26
GENERAL PARTNER         21
NOT APPLICABLE          11
EXECUTIVE DIRECTOR      10
TRUSTEE                  6
BENEFICIARY              4
Name: count, dtype: int64

In [ ]:
#Derivar el mismo resultado a partir de agrupar

# Agrupar por la columna 'title' y dar un conteo por 'account'


# Ordenar de manera descendente


# Imprimir el resultado

## Uniendo multiples DataFrames
<p>Tu objetivo es encontrar el número total de viajes proporcionados a los pasajeros que pasan por la estación Wilson <code>station_name == 'Wilson'</code> cuando viajan en el sistema de transporte público de Chicago los días de semana <code>day_type == 'Weekday'</code> en julio <code>mes == 7</code> . Afortunadamente, Chicago proporciona estos datos detallados, pero están en tres tablas diferentes. Trabajarás en fusionar estas tablas para responder la pregunta, toda la información que necesitas para responder la pregunta se encuentra en las tablas <code>cta_calendar</code>, <code>cta_ridership</code> y <code>stations</code></p>
<p>
<img src="https://assets.datacamp.com/production/repositories/5486/datasets/56b5ecb2edcdc896c69effdf05ef65e5454ff996/cta_L_diagram.png" width="550">
</p>

In [37]:
# Importa datasets
cal = pd.read_pickle(
    r"C:\Users\usuario\OneDrive\Escritorio\Python repositorios\python-basics\Data excel para manejo de librería Pandas\Data\cta_calendar.p"
)
ridership = pd.read_pickle(
    r"C:\Users\usuario\OneDrive\Escritorio\Python repositorios\python-basics\Data excel para manejo de librería Pandas\Data\cta_ridership.p"
)
stations = pd.read_pickle(
    r"C:\Users\usuario\OneDrive\Escritorio\Python repositorios\python-basics\Data excel para manejo de librería Pandas\Data\stations.p"
)

In [38]:
# imprime los primeros 5 registros
display(cal.head(5))
display(ridership.head(5))
display(stations.head(5))

   year  month  day        day_type
0  2019      1    1  Sunday/Holiday
1  2019      1    2         Weekday
2  2019      1    3         Weekday
3  2019      1    4         Weekday
4  2019      1    5        Saturday

  station_id  year  month  day  rides
0      40010  2019      1    1    576
1      40010  2019      1    2   1457
2      40010  2019      1    3   1543
3      40010  2019      1    4   1621
4      40010  2019      1    5    719

  station_id        station_name                 location
0      40010  Austin-Forest Park  (41.870851, -87.776812)
1      40020         Harlem-Lake  (41.886848, -87.803176)
2      40030        Pulaski-Lake  (41.885412, -87.725404)
3      40040        Quincy/Wells   (41.878723, -87.63374)
4      40050               Davis   (42.04771, -87.683543)

In [40]:
# Une las tres tablas
union= ridership.merge(cal, on = ['year', 'month', 'day'], how = 'inner'). merge (stations, on = 'station_id', how= 'inner')
display(union.head(5))
# Crea el filtro para la estacion Wilson, todos los días entre semana de julio (Como se menciona arriba)

# filtrar los viajes y suma para obtener el total

,station_id,year,month,day,rides,day_type,station_name,location
0,40010,2019,1,1,576,Sunday/Holiday,Austin-Forest Park,"(41.870851, -87.776812)"
1,40010,2019,1,2,1457,Weekday,Austin-Forest Park,"(41.870851, -87.776812)"
2,40010,2019,1,3,1543,Weekday,Austin-Forest Park,"(41.870851, -87.776812)"
3,40010,2019,1,4,1621,Weekday,Austin-Forest Park,"(41.870851, -87.776812)"
4,40010,2019,1,5,719,Saturday,Austin-Forest Park,"(41.870851, -87.776812)"